### ISSUE TITLE
Brightness control works on one of two identical monitors

### ISSUE THREAD

**Issue by leecbaker** [MonitorControl/MonitorControl#286] opened 2020-09-10 17:56 UTC
**Checklist**

- [X] I have searched for existing issues
- [X] I have looked through [the Monitor Troubleshooting wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] I have updated MonitorControl to the latest version (using v2.0.0 via homebrew)

**Describe the issue**
Brightness control works only for one monitor. When changing the brightness, the HUD appears on both monitors, and the MonitorControl menu shows the brightness being lower on both, but the actual brightness on one of the monitors remains unchanged.

**Expected behavior**
When pressing the brightness buttons on my keyboard, i expected brightness to change on both monitors simultaneously. Instead, only one monitor's brightness changes.

**Additional context**
Monitors are in 4K60 HDR mode.
```
Radeon Pro 560X:

  Chipset Model:	Radeon Pro 560X
  Type:	GPU
  Bus:	PCIe
  PCIe Lane Width:	x8
  VRAM (Total):	4 GB
  Vendor:	AMD (0x1002)
  Device ID:	0x67ef
  Revision ID:	0x00c2
  ROM Revision:	113-C980AL-075
  VBIOS Version:	113-C97501U-005
  EFI Driver Version:	01.A1.075
  Automatic Graphics Switching:	Supported
  gMux Version:	5.0.0
  Metal:	Supported, feature set macOS GPUFamily2 v1
  Displays:
LU28R55:
  Resolution:	5120 x 2880 (5K/UHD+ - Ultra High Definition Plus)
  UI Looks like:	2560 x 1440 @ 60 Hz
  Framebuffer Depth:	30-Bit Color (ARGB2101010)
  Display Serial Number:	HCHN400389  
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Rotation:	Supported
  Automatically Adjust Brightness:	No
  Connection Type:	Thunderbolt/DisplayPort
LU28R55:
  Resolution:	5120 x 2880 (5K/UHD+ - Ultra High Definition Plus)
  UI Looks like:	2560 x 1440 @ 60 Hz
  Framebuffer Depth:	30-Bit Color (ARGB2101010)
  Display Serial Number:	HCHN400414  
  Mirror:	Off
  Online:	Yes
  Rotation:	Supported
  Automatically Adjust Brightness:	No
  Connection Type:	DVI or HDMI
  Adapter Firmware Version:	0.00
```

**Environment Information (please complete the following information):**
 - macOS version: 10.15.6 (19G2021)
 - MonitorControl version: v2.0.0 build 640
 - Monitor(s): 2x Samsung LU28R55 
 - Mac model: MBP 15" 2019
 - Monitor Cable(s)/Connection(s): HDMI via Aukey Unity PD 9-Port USB-C Hub

**Comment by harishperfect** [comment] 2020-09-17 23:26
I second this! I have two HP Envy 27 Inch monitors with proper DP cables. Can confirm only works for 1 monitor.

**Comment by leecbaker** [comment] 2020-09-18 16:53
Another clue to what's happening here. If I adjust the brightness for the first monitor listed in the menu, it changes the brightness only for one monitor. Changing the brightness for the second monitor listed also changes the same monitor.

Perhaps brightness changes are only applied to the first monitor of each make/model?

<img width="359" alt="image" src="https://user-images.githubusercontent.com/1047159/93624139-7bca5880-f9a5-11ea-93fd-a5fa014dd166.png">

**Comment by JoniVR** [comment] 2020-09-19 11:46
Duplicate of #49

**Closed by JoniVR** 2020-09-19 11:46 UTC
Labels: Type: Monitor Issue
