### ISSUE TITLE
Doesn't Function on M1 Mac

### ISSUE THREAD

**Issue by thegrownupgeek** [MonitorControl/MonitorControl#332] opened 2020-11-24 21:24 UTC
Hi, Thanks for the product which I have used for years on my Mac mini with my Samsung C34J791 Monitor and was functional on Big Sur.  Today I received a new M1 MacBook Pro.  The app will not recognise the monitor or allow for control.

**Comment by JoniVR** [comment] 2020-11-24 21:27
Duplicate of #323, see tracking in that issue 🙂

**Closed** 2020-11-24 21:27 UTC
