### ISSUE TITLE
Option to hide brightness slider

### ISSUE THREAD

**Issue by ckilb** [MonitorControl/MonitorControl#616] opened 2021-09-23 15:10 UTC
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

I only want to use MonitorControl to change the volume of my monitor's speaker.
Sometimes I by mistake change the brightness instead. I'd love to have an option to remove the brightness sliders from the menu.

### Describe the solution you'd like

There's already an option "Show volume slider in menu" and "Show contrast slider in menu".
I think it would be consistent to add another option "Show brightness slider in menu".

### Describe alternatives you've considered

I don't see a real alternative here.

### Anything else?

By allowing to hide the brightness sliders there's a chance a user will disable all of the sliders which makes the menu nearly useless beside the options to quit the app or open preferences dialog. 
It may be worth to think about changing the "Menu contents" selection a little bit so the user is not able to disable all the options. I'd could imagine a dropdown instead of checkboxes or some simple validation could do the job.

**Comment by waydabber** [comment] 2021-09-23 16:22
Hi, the unreleased 4.0.0 version already has this feature. There is an [interim build (unsigned)](https://github.com/MonitorControl/MonitorControl/discussions/596) at the bottom of the opening post here. You can add your feedback in the discussion.

You need to enable Advanced options and  unclick "Show brightness slider".

<img width="803" alt="Screen Shot 2021-09-23 at 18 15 25" src="https://user-images.githubusercontent.com/37590873/134544940-841a8f38-8cf6-4090-ade0-01de8f741718.png">

(This is a duplicate of https://github.com/MonitorControl/MonitorControl/issues/324 so I'll close it)

Thank you!

**Closed by waydabber** 2021-09-23 16:22 UTC
Labels: Duplicate, Feature Request
