### ISSUE TITLE
Broken control on unplug

### ISSUE THREAD

**Issue by tarikaltuncu** [MonitorControl/MonitorControl#320] opened 2020-11-12 06:16 UTC
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [x] I have updated MonitorControl to the latest version

**Describe the bug**
App works great when plugged. However, brightness control buttons stop working for the internal monitor when I unplug both external monitors. To fix the issue, I have to quit from the monitorcontrol app.

**To Reproduce**
1. Install the app
2. Plug your mac to external monitor
3. Unplug the monitor
4. Try using the brightness buttons

**Expected behavior**
It should continue working 

**Environment Information (please complete the following information):**
 - macOS version: Catalina
 - MonitorControl version: 2.1.0
 - Monitor(s): Asus PB298Q and Dell U2711b monitors

**Comment by JoniVR** [comment] 2020-11-22 12:50
You're right, I'm only seeing your issue now but I have run into this issue myself. It's probably a duplicate of #327, so let's continue tracking this on that issue.

**Closed by JoniVR** 2020-11-22 12:50 UTC
Labels: Type: Bug
