### ISSUE TITLE
With Four External Monitors - Only three working

### ISSUE THREAD

**Issue by CharlesCCC** [MonitorControl/MonitorControl#417] opened 2021-03-28 05:03 UTC
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the Monitor Troubleshooting wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [x] I have updated MonitorControl to the latest version

**Describe the issue**
I have connected my mac with 4 external monitors (2 via Displayport + 2 via HDMI) 
Regardless how I connect all those four monitor, only three out of four is able to adjust the brightness. 

**Expected behavior**
i expect all four monitors to change brightness at the same time. 

**Screenshots**
N/A

**Additional context**
Any three combination will working (2 Displayport + 1 HDMI, or 2 HDMI + 1 Displayport). but not the 4th one. It felts like the App is limited to only allow control the Max 3 monitors at the same time. 

**Environment Information (please complete the following information):**
 - macOS version: 11.2.3
 - MonitorControl version: 2.1.0 (latest)
 - Monitor(s): Two AOC U2790B - 4k, Two Lenovo ThinkVision P27q-20 
 - Mac model: iMac 27inch 2019 (with 580x GPU)
 - Monitor Cable(s)/Connection(s): (e.g. DisplayPort): 2 displayport, 2 HDMI (tried switch them around, made no difference) 

Thank you for created this great open source app.

**Comment by waydabber** [comment] 2021-08-20 18:26
There is no such limitation built in. The display detection logic is rewritten in 3.0.0 (hopefully it will soon be released) - I'd advice to try if it helps or not. Please give a feedback whether things improved or not! Thank you!

**Comment by waydabber** [comment] 2021-08-25 16:25
Hi, there seems to be an issue on the Intel side about supporting identical displays, so this issue is probably a duplicate of that one:

#49 

I'll close this issue for now but please feel free to comment if there is anything we can do or if we should reopen this issue. You can comment or test the fix if available under #49! Thank you!

**Closed by waydabber** 2021-08-25 16:25 UTC
Labels: Bug, Feedback/info required!
