### ISSUE TITLE
Volume changes by six steps instead of one with LG 32UL750-W

### ISSUE THREAD

**Issue by thekeith** [MonitorControl/MonitorControl#253] opened 2020-07-10 02:29 UTC
**Checklist**
- [x] I have searched for existing issues
- [x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [x] I have updated MonitorControl to the latest version

**Describe the bug**
Using an LG 32UL750-W monitor, when I adjust the volume up/down via keyboard it changes the monitor volume value in units of six instead of one.

**To Reproduce**
1. Connect an LG 32UL750-W monitor
2. Adjust volume

**Expected behavior**
Volume steps should be in increments of one

**Screenshots**
(no screenshots as it is the OSD the is changing - can send a video directly if needed)

**Environment Information (please complete the following information):**
 - macOS version: 10.15.5
 - MonitorControl version: 2.0.0
 - Monitor(s): LG 32UL750-W

**Comment by inf0dr0id** [comment] 2020-07-10 05:48
Duplicate of #111 and #120

**Closed** 2020-07-10 08:41 UTC
Labels: Type: Bug, Type: Duplicate
