### ISSUE TITLE
Acer X34P name not detected, but it is visible using ddccdl

### ISSUE THREAD

**Issue by wojciechczyz** [MonitorControl/MonitorControl#313] opened 2020-10-23 19:18 UTC
**Checklist**

- [X] I have searched for existing issues
- [X] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] I have updated MonitorControl to the latest version

**Describe the bug**
I have external Acer X34P connected, MonitorControl displays name as Unknown. However using ddccdl I can see monitor name:
ddcctl -d 1
D: NSScreen #478260293 (3440x1440 0°) 109.00 DPI
I: found 1 external display
I: polling display 1's EDID
I: got edid.serial: #ASMUeGST5VPd
I: got edid.name: Acer X34 P

**To Reproduce**
Connect Acer X34P
Run Monitor Control. In menu, monitor name is Unknown. In Display preferences table, Name and Display Name are both Unknown

**Expected behavior**
X34P displayed in Menu and preferences window

**Additional context**
using ddccdl I can see monitor name:
ddcctl -d 1
D: NSScreen #478260293 (3440x1440 0°) 109.00 DPI
I: found 1 external display
I: polling display 1's EDID
I: got edid.serial: #ASMUeGST5VPd
I: got edid.name: Acer X34 P

**Environment Information (please complete the following information):**
 - macOS version: Mac OS Catalina 10.15.7
 - MonitorControl version: 2.1.0 721
 - Monitor(s): Acer X34P

**Comment by waydabber** [comment] 2021-08-21 17:00
Hey, we tweaked the display detection logic a bit in 3.0.0. Can you please test the new version and confirm if the issue is still present or can be closed? Thank you!

**Comment by waydabber** [comment] 2021-08-25 16:31
I'll close this issue for now but please feel free to comment if there is anything we can do. If the issue persists, we can reopen this issue! Thank you!

**Closed by waydabber** 2021-08-25 16:31 UTC
Labels: Monitor Issue, Feedback/info required!

**Comment by ellieplz** [comment] 2022-09-09 15:15
hello! sorry to reopen, but issue persists on Acer x34. 

ddctl brings up:
D: CGDisplay 95277898-4B8B-4E72-AB59-326B415E514F dispID(#3) (3440x1440 0°) 109.00 DPI
I: found 1 external display

brightness works but only between 0 and 50%, anything above 50% is just set to max.

**Comment by the0neyouseek** [comment] 2022-09-14 15:17
Hi @ellieplz , If you are using a mac m1/m2 please make sure tu use an usb-c cable and not an HDMI one as this may be the reason for your issue. The HDMI port on these models does not allow for ddc control (hardware). Your other option would be to uncheck the "use hardware ddc control" checkbox in MonitorControl preferences
