### ISSUE TITLE
Clipped border in the preferences in some localizations

### ISSUE THREAD

**Issue by stiiveo** [MonitorControl/MonitorControl#655] opened 2021-10-02 06:56 UTC
### Before opening the issue, have you...?

- [x] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

I combine these two issues into one ticket cause I think they're both minor issues.
1. Missing localization: 
    The placeholders of the buttons for recording keyboard shortcut are not localized.
![Screen Shot 2021-10-02 at 2 46 12 PM](https://user-images.githubusercontent.com/22095596/135706661-2c8b6822-e56e-4b7e-9f36-49dff1d8d116.png)
2. UI's Trailing border in the Displays section is clipped.
![Screen Shot 2021-10-02 at 2 46 52 PM](https://user-images.githubusercontent.com/22095596/135706693-1916819b-7f13-4e2f-baf6-cdf340840b0e.png)

### Steps to reproduce

They are both visible right in the Keyboard and Displays section of the preferences panel.

### Expected behavior

1. Make the placeholders of the aforementioned buttons localizable.
2. Resolve the layout clipping issue in the Displays section.

### Environment Information (please complete the following information)

```markdown
- macOS version: 11.6 Big Sur
- Mac model: MacBook Air 2020
- MonitorControl version: 4.0.0 Build 6308
- Monitor(s): Dell U2719D
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment] 2021-10-02 07:48
Hi @stiiveo 

I can't seem to reproduce the clipping issue. I thought it might be becaused of the enabled mouse scrollbar but still it doesn't seem to do that with me. Is it happening only with Chinese language? Thank you!

<img width="803" alt="Screen Shot 2021-10-02 at 9 48 15" src="https://user-images.githubusercontent.com/37590873/135708259-7d8a0755-67cc-41da-8fa5-594aed5bf8f6.png">

**Comment by stiiveo** [comment] 2021-10-02 08:06
That seems to be the case. If I switch the language back to English the issue disappears.
![Screen Shot 2021-10-02 at 4 05 28 PM](https://user-images.githubusercontent.com/22095596/135708710-13104832-2fbb-46ed-a135-354e3508378e.png)

**Comment by waydabber** [comment] 2021-10-02 08:06
Regarding the keyboard shortcuts box, localizations should be added here:

https://github.com/sindresorhus/KeyboardShortcuts/tree/main/Sources/KeyboardShortcuts/Localization

For more information see this: https://github.com/sindresorhus/KeyboardShortcuts#localization

This is a separate project, but once the localization is accepted by that repository, it will be incorporated into MonitorControl as well.

**Comment by waydabber** [comment] 2021-10-02 08:08
> That seems to be the case. If I switch the language back to English the issue disappears.

Great. This way I can reproduce it and try to fix it. Thank you!

**Comment by waydabber** [comment] 2021-10-02 08:14
I added the info regarding the shortcuts localization to the tutorial https://github.com/MonitorControl/MonitorControl/discussions/637 and used your screenshot with your implied permission. :)

**Comment by stiiveo** [comment] 2021-10-02 08:15
> Regarding the keyboard shortcuts box, localizations should be added here:
> 
> https://github.com/sindresorhus/KeyboardShortcuts/tree/main/Sources/KeyboardShortcuts/Localization
> 
> For more information see this: https://github.com/sindresorhus/KeyboardShortcuts#localization
> 
> This is a separate project, but once the localization is accepted by that repository, it will be incorporated into MonitorControl as well.

Great! I'll dive into that one if I could find some time.

**Comment by waydabber** [comment] 2021-10-02 17:29
I moved around the layout a bit + fixed other clipped text on that view which sometimes occured. Now it seems ok to me:

<img width="803" alt="截圖 2021-10-02 19 26 33" src="https://user-images.githubusercontent.com/37590873/135726547-9669dc5c-6028-455d-84b4-8cb72e8c92e1.png">

But please test (it is in the `fixes/general` branch)

**Comment by stiiveo** [comment] 2021-10-03 05:08
Thanks for the quick fix!
I've tested the Chinese (Traditional, Taiwan) localization and no clipping issue is visible. 👍

To ensure that no clipping issue occurs in other translations, I tested other supported languages and could still spot the clipping issues.

(The following screenshots are taken with Dutch localization)
![Screen Shot 2021-10-03 at 11 57 38 AM](https://user-images.githubusercontent.com/22095596/135740377-edcc84fb-541e-48c1-a42a-829a20ef19bc.png)
![Screen Shot 2021-10-03 at 12 40 35 PM](https://user-images.githubusercontent.com/22095596/135740397-bdba907b-8187-4241-9903-bb1d3aed28f6.png)
![Screen Shot 2021-10-03 at 12 41 29 PM](https://user-images.githubusercontent.com/22095596/135740441-3cc92071-c5f3-4ccd-8263-d055c4addeee.png)

The issue can be seen in **General**, **App menu**, **Keyboard** and **Displays** sections in the following languages:
Dutch, French, German, Italian

The issue can only be seen in **Displays** section in the following languages but they're mostly only partially translated:
Polish, Russian, Spanish(Latin America), Turkish

I hope the info above could make it easier for you to debug it. :)

**Comment by stiiveo** [comment] 2021-10-03 05:20
I'm not sure if it's appropriate to make a suggestion here but since it's related to this issue, I'd just put it here. 

I think a bit more margin on the right hand side of the panel should make it easier for the users to read the text content. To me the line is a bit too long. But I'm also aware that if the line breaks too soon and the text count is big, it could make the panel stretches too long. So a right balance has to be found here.
![Screen Shot 2021-10-03 at 12 35 49 PM](https://user-images.githubusercontent.com/22095596/135740909-a2ae76a7-f2d7-4757-b4fa-55749919f710.png)

**Comment by waydabber** [comment] 2021-10-03 07:41
@stiiveo wow some languages are indeed verbose. :)

The problem is, checkbox lables don't support wraps layout as simple labels do so they can't wrap to two lines if needed expanding the layout. This could be done programmatically for each item but it would be a pain to implement. :)

I guess I could add a little more space but I did want to preserve the feeling of a Preferences window and making it too wide somehow deducts from that.

@JoniVR - Is it possible to just make the Dutch translation in some of these options just a tiny bit more succinct? If the language permits of course. I know it's hard since Hungarian is a verbose language as well (compared to English) and I had to be creative here and there as well. :)

**Comment by waydabber** [comment] 2021-10-03 09:41
I did make the width wider (with about 40 pixels and rearranged everything so labels would have more space in them. I also shifted the divide on the first three panes a bit left for even more space on the right column.

**Comment by waydabber** [comment] 2021-10-03 09:49
Still there are some Dutch text that are clipping but the situation is better. :) I'll leave it to @JoniVR whether these texts can be shortened a bit.

<img width="842" alt="Schermafbeelding 2021-10-03 om 11 47 03" src="https://user-images.githubusercontent.com/37590873/135748501-98988b74-a833-4223-adfa-ba433f94c4c6.png">
<img width="842" alt="Schermafbeelding 2021-10-03 om 11 47 08" src="https://user-images.githubusercontent.com/37590873/135748503-51fed715-7565-4838-b1ff-5dd4114bde9e.png">
<img width="842" alt="Schermafbeelding 2021-10-03 om 11 47 14" src="https://user-images.githubusercontent.com/37590873/135748504-f0c41ee6-964c-4fb6-b0e8-ff60c4c90ec8.png">
<img width="842" alt="Schermafbeelding 2021-10-03 om 11 46 59" src="https://user-images.githubusercontent.com/37590873/135748497-5483537d-930f-47f5-83f1-78f8f4e2e12c.png">

**Comment by waydabber** [comment] 2021-10-03 09:50
Again, thanks @stiiveo for your input and care!

**Comment by JoniVR** [comment] 2021-10-03 10:23
> Still there are some Dutch text that are clipping but the situation is better. :) I'll leave it to @JoniVR whether these texts can be shortened a bit.

I mean technically I could, but that doesn't seem like a very good solution to me? 

Ideally, it would wrap as necessary, we can't really ask every translator to shorten their translations due to length differences.

**Comment by stiiveo** [comment] 2021-10-03 10:29
If you want to limit the max height of the panel, maybe consider making the panel scrollable if the intrinsic size pass the threshold?

**Comment by waydabber** [comment] 2021-10-03 10:30
Yes, wrapping would be the optimal solution. The normal text labels do wrap but unfortunately the checkbox labels do not wrap (or they do wrap if we force them but don't change their frame height even then). I can try programmatically iterate through all checkbox labels and set their height manually once the initial rendering is completed though. This will work on the first three panes but not on the Displays tab as that does not use gridview (gridview will adapt to the contents if needed and the view constraints are tied to the GridView height - this was needed to be able to dynamically show/hide advanced preferences).

**Comment by waydabber** [comment] 2021-10-03 10:32
@stiiveo the problem is how the checkbox label itself works by default, not the panel (which is dynamic as of now and adapt automatically). There is a programatic way to handle this if this is really what we want (I can disable autoresizing on all checkboxes, render them, figure out the number of lines that resuls after translation and dynamically multiply the default height by the number of lines).

**Comment by JoniVR** [comment] 2021-10-03 10:37
What could technically also work to wrap checkboxes is using a checkbox (with no text), adding a label next to it in a StackView and adding a click gesture recognizer to the StackView as a custom component.. though that might be a bit overkill? Not sure. 

Again, I can probably shorten the translation, but to me it seems like other languages will/are facing the same issue. Perhaps the items in general can be shortened a bit somehow? We wouldn't have to throw away translations if we just shorten the base since it would still mean the same thing. 

Just trying to find a solution that's going to be easiest to work with in the future.

**Comment by stiiveo** [comment] 2021-10-03 10:43
I can see your point. But there's also another thing needed to be considered. If new box or label were added to anyone of the tabs in the future or somehow the string count is enormously large,it would make the panel infinitely long until the content is fully enclosed.

**Comment by waydabber** [comment] 2021-10-03 10:49
@stiiveo I think we can't add any more stuff to these panes (in advanced mode). I was on the verge of moving all combined control/syncing related stuff to a separate "Sync" pane but eventually decided against it. In one of the next versions I think we'll move to an entirely different layout (sidebar on the left for category + scrollable view with options on the right) which will be super flexible.

@JoniVR - well I feel that is a bit overkill + again, it won't work in the Displays tab anyway (unless we doo a complete redesign - which might be needed anyway as the current layout is not entirely logical, the advanced part is mostly relevant for DDC displays for example but still is present in disabled form for all other displays).

I think the simpler solution would be to just shorten the text for now and when we do the full Prefpanes redesign, we'll aim for a fully dynamic approach - I would not pour more energy into fixing this one as ultimately the current layout is a dead-end I think.

**Comment by JoniVR** [comment] 2021-10-03 10:51
Agreed we can't keep making panels longer and adding tabs infinitely, Xcode preferences does seem to do some minor scrolling here and there, so that might indeed be a solution, though I do hope we're about "feature-complete" at this point besides from a few more settings that are heavily requested. Can't keep adding settings infinitely either.

**Comment by JoniVR** [comment] 2021-10-03 10:52
I think the simpler solution would be to just shorten the text for now and when we do the full Prefpanes redesign, we'll aim for a fully dynamic approach - I would not pour more energy into fixing this one as ultimately the current layout is a dead-end I think.

Seems good to me, when do you propose a redesign? Because that would probably be another major change then, are we planning v5.0.0 already? 😂

**Comment by stiiveo** [comment] 2021-10-03 11:04
If so you guys need to put some text count limit in the readme as well 😂

**Comment by waydabber** [comment] 2021-10-03 11:07
Well, I'd leave the redesign for a future major release, yes, definitely not during this beta cycle. :)

I'd also like to refactor how displays control works in general (the current AppleDisplay/OtherDisplay approach is still not logical, even though I tried to make things more unified in this release) and make it more flexible - we should have a simple Device with pluggable control options. For example some displays can be controlled vida CoreDisplay, DDC, Gamma and shading as well, each has its own drawbacks and benefits - like shading does not break f.lux while gamma does, etc. It would be great if the user could choose the control method. Also volume control might have multiple methods in the future and contrast control can be done using Gamma and DDC. There are devices that support only brightness or only volume (like other digital devices, like AV receivers). The architecture should be extensible and we should devise an interface that is straightforward for general users but customizable for Expert users (btw we could rebrand 'Advances settings' to 'Expert or PRO options' which might have a better ring to it).

There are a lot of feature things we could implement to make things even better. But I understand that we want to avoid making MonitorControl overly bloated (some might feel that even implementing all these feature requests was a bit too much). :)

**Comment by waydabber** [comment] 2021-10-03 11:10
_But before everybody starts to worry that I'll start rewriting everything again like crazy, I am actually trying to restrain myself as I feel MC took too much of my focus lately which is not entirely balanced considering all the other things I should be doing. :)_

**Comment by stiiveo** [comment] 2021-10-03 11:59
@waydabber There's always new feature to be added. Prioritize your things first. Yes it's good to have the features you mentioned but I believe the app as of now meets majority's needs. Not every user is expert right? ;)

**Comment by waydabber** [comment] 2021-10-03 12:44
Hey @stiiveo thanks for the advice. Btw, I don't feel this as a burden at all (the problem is I seem to enjoy coding too much). :)

**Comment by JoniVR** [comment] 2021-10-03 15:16
Perhaps this is something where we could ask some help from UX specialists in the community (for layout changes in the future that is).

**Closed** 2021-10-03 15:17 UTC
Labels: Type: Bug, Status: Done
