### ISSUE TITLE
Doesn't detect monitors on MacbookPro M1

### ISSUE THREAD

**Issue by shelomohkhual** [MonitorControl/MonitorControl#380] opened 2021-01-28 05:08 UTC
**Checklist**

- [ ] I have searched for existing issues
- [ ] I have looked through [the Monitor Troubleshooting wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [ ] I have updated MonitorControl to the latest version

**Describe the issue**
A clear and concise description of the problem.

**Expected behavior**

**Screenshots**
<img width="1063" alt="Screenshot 2021-01-28 at 1 03 12 PM" src="https://user-images.githubusercontent.com/49126015/106092704-d05abd00-6169-11eb-9da7-9a85f24442d6.png">

**Additional context**

**Environment Information (please complete the following information):**
 - macOS version:
 - MonitorControl version:
 - Monitor(s):
 - Mac model:
 - Monitor Cable(s)/Connection(s): (e.g. DisplayPort)

**Comment by cnliucheng** [comment] 2021-01-29 01:13
me too

**Comment by robbsie** [comment] 2021-01-30 09:13
See #323

**Comment by hroland** [comment] 2021-01-30 16:21
dupe of #323

**Closed** 2021-01-30 16:21 UTC
Labels: Type: Monitor Issue

**Comment by outsiderz** [comment] 2021-03-17 23:46
+
