### ISSUE TITLE
Modifier keys for volume control have no effect

### ISSUE THREAD

**Issue by pointlessone** [MonitorControl/MonitorControl#222] opened 2020-05-14 18:43 UTC
Option/Shift modifiers have no effect, volume changes in increments of 6.

**Comment by rafael-trevisan** [comment] 2020-05-16 22:09
Same thing here using Catalina

**Comment by pointlessone** [comment] 2020-06-14 17:19
* MonitorControl 2.0.0 (build 640)
* macOS Catalina 10.15.4 (19E287)
* Keyboard: ErgoDox Infinity with QMK firmware. Keys send proper media key presses and Opt/Shift are definitely registered.
* Display: LG 31MU97 connected over DisplayPort

Additional note: Brightness *does* change at smaller increments when Opt+Shift is pressed.

**Comment by zsiegel92** [comment] 2020-08-17 01:44
I do not have any issue with <kbd Option >Option</kbd> + <kbd Shift>Shift</kbd> (smaller increments) but I *do* have this issue for <kbd Shift>Shift</kbd> (sound effect while changing volume).

The expected behavior when holding <kbd Shift>Shift</kbd> and pressing volume keys is for a small sound effect to play. There is a setting for the volume key to always make this sound effect, in which case holding <kbd Shift>Shift</kbd> inverts the setting and *doesn't* play the sound effect.

For me, the sound effect plays when the setting for it to play by default is checked; when that setting is not checked, holding <kbd Shift>Shift</kbd> does not play the sound effect.

**Comment by JoniVR** [comment] 2020-09-19 12:01
I'm going to mark this as a monitor issue for now as it works fine for most people (I think), if anyone else runs into this, please post here and provide detailed information about your setup (monitor, mac, macOS version, ...).

@zsiegel92 I can confirm this, can you open a separate issue for this?

**Comment by waydabber** [comment] 2021-08-21 16:18
I'll close this issue due to low activity, but feel free to open a new one or respond if it is still a problem! Thank you!

**Closed by waydabber** 2021-08-21 16:18 UTC
Labels: Monitor Issue
