### ISSUE TITLE
Only one monitor of two (same model) can be adjusted.

### ISSUE THREAD

**Issue by mebemellow** [MonitorControl/MonitorControl#326] opened 2020-11-20 16:54 UTC
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the Monitor Troubleshooting wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [x] I have updated MonitorControl to the latest version

**Describe the issue**
I use two monitors of exactly the same model (Asus Proart PA24A). On the first one I can adjust the brightness, but when I change to the second one I change the brightness of the other one again. This also happens when I adjust all monitors at the same time. I can only adjust one monitor, its always the same.

**Expected behavior**
Brightness is adjustable on each selected monitor 

**Additional context**
Could it be that by using the same monitor model both screens get the same ID?
Accordingly, only one could be adjusted.

**Environment Information (please complete the following information):**
 - macOS version: 10.15.7
 - MonitorControl version: 2.1.0
 - Monitor(s): Asus Proart PA24A
 - Mac model: MacBook Pro (15-inch, 2018)
 - Monitor Cable(s)/Connection(s): usb-c to usb-c

**Comment by JoniVR** [comment] 2020-11-20 16:58
Duplicate of #49

**Closed** 2020-11-20 16:58 UTC
Labels: Type: Duplicate
