### ISSUE TITLE
Monitor not working/detected consistently (HP Z27)

### ISSUE THREAD

**Issue by lukees** [MonitorControl/MonitorControl#135] opened 2019-10-01 16:12 UTC
Monitore: HP Z27
Laptop: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
MacOS: 10.14.6
Connection: USB-C

This has happened twice now. The first time, I had my MacBook connected for a few days and didn't have the issue until I disconnected it, took it out, and tried hooking it back up. It wouldn't detect it and eventually, after restarting my computer a few times, quitting the MonitorControl app, factory-resetting the monitor, and then trying an HDMI connection (to confirm the monitor in fact worked), it just worked. No clue how.

I didn't experience any issues until yesterday I tried using the MonitorControl app again (which works and is great).

**Comment by lukees** [comment] 2019-10-01 16:28
I tried rebooting, factory-resetting, and using the HDMI connection, and still cannot get my monitor to detect my MacBook over USB-C, though it still sends power to it.

**Comment by JoniVR** [comment] 2019-10-01 21:36
So it worked before with the exact same setup? You didn't change anything? 
Didn't update the app? These issues can be pretty hard to debug especially without having physical access.. 

Also, what MonitorControl version? 

I'd suggest testing with [ddcctl](https://github.com/kfix/ddcctl), reporting results here first.

You'd probably have to find a way to reproduce this happening before we can even guess what's happening there.

**Comment by lukees** [comment] 2019-10-01 21:50
Yeah, I'm not sure how this would be debugged. I'm just hoping someone else runs into the issue and shares a solution with me.

This second time around I didn't do anything new (like I didn't the last time). I ran the app, it saw my monitor, I played with the brightness and it worked great. Then later, I unplugged my MacBook from the monitor (it connects via USB-C for power, IO, and display) took it out to use it at a cafe. Then when I returned and plugged it in, the monitor was no longer recognized over USB-C, though the power and IO continue to work.

While this doesn't prove anything, it's hard to imagine that twice, I would have done something else that would have caused this issue other than my sudden use of your app.

Is there anything that it does that I can clean up? Any plist files or command line flags it enables?

I unfortunately deleted the app and emptied my trash before your comment so I'm not able to tell you what version I was running, but I know I installed it within the past month or so.

**Comment by JoniVR** [comment] 2019-10-13 21:40
Try on 1.7.0 and let me know, there isn't anything as far as I'm aware that you need to manually remove that could have an impact on your issue.

**Comment by meteochu** [comment] 2020-07-10 23:56
Did you ever find a solution to this? I just installed Version 2.0.0 and I'm running into the same issue with my HP Z27. USB-C works for the USB-related things but the DP alt-mode is completely screwed and won't turn on. Also won't connect with iPad either so it seems like it screwed up something on the monitor itself.

**Comment by lukees** [comment] 2020-07-11 16:45
@meteochu Ah no, I honestly just stopped using this tool cuz I was scared I'd lose the ability to connect 😢

**Comment by meteochu** [comment] 2020-07-11 18:50
@lukees Ah bummer. I ended up trying to reset everything setting I could think of on my Mac and the monitor. Also restarted them a couple of times and USB-C DP Alt Mode came back eventually after I did something. Too afraid to try again or to reproduce though. 😰

**Comment by jakedt** [comment] 2020-10-14 13:28
I also experience this issue with the HP z27 (4k version). The thing that gets it to consistently come back for me is to unplug the monitor until the power light goes out, and then plug it back in. I would LOVE to be able to use this tool, but as for now it makes my setup unusable.

@JoniVR Can we reopen this? I can reproduce it pretty reliably, I just have to use MonitorControl to control brightness once and the next time I unplug my computer and plug it back in the monitor won't recognize it.

**Comment by JoniVR** [comment] 2020-10-14 19:33
@jakedt I reopened it but if it's a problem with the monitor's implementation I'm afraid there's little we can do about it.

**Comment by reverson** [comment] 2021-03-07 19:41
This issue happens on my HP Z-27 monitor as well.  When using `ddcctl` I am able to set the brightness correctly, and when I plug and unplug the monitor comes back as expected. Weirdly after using `ddcctl` I am unable to quickly reproduce the unplug and replug issue with MonitorControl as well.  Might be worth a shot just using `ddcctl` once and attempting to use MonitorControl again (but I'll continue doing more testing).

```
./ddcctl -d 1 -b 50
```

**Comment by vimota** [comment] 2021-05-06 04:46
I'm also having this issue - after using MonitorControl my HP Z-27 no longer recognizes my Macbook Pro 16inch. I tried connecting my Macbook Air and it worked but I still can't get the monitor to recognize the Macbook Pro 😕

**Comment by vimota** [comment] 2021-05-06 04:50
Oh turns out, after uninstalling MonitorControl and restarting the computer it works!

**Comment by waydabber** [comment] 2021-08-21 16:25
Hi all, the all new version 3.0.0 has improved display detection logic and better handles configuration changes and sleep scenarios. I'll close this issue for now but if any problem arises, please feel free to open a new specific Issue. Thank you!

**Closed by waydabber** 2021-08-21 16:25 UTC
Labels: Monitor Issue

**Comment by mravcak** [comment] 2023-02-22 13:46
Unfortunately, the problem seems to be still present even in the latest version. After using the Monitor Control for the first time and then disconnecting and reconnecting, the display doesn't work. Only after removing it from electrical source and plugging it back in or switching it on/off with hardware switch on the back of the display, the display connects again (simply turning on/off doesn't work).

What worked for me on my Z27 was setting _DCC read polling mode_ to _None_ in the preferences of MonitorControl. Now it works as expected.
