### ISSUE TITLE
Not support for stage manager of Mac OS13

### ISSUE THREAD

**Issue by sheyu921** [MonitorControl/MonitorControl#1091] opened 2022-06-25 17:50 UTC
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

This is a really good tool for multi-monitors. However, I found that when I open the tool, the sidebars of the stage manager will disappear from the main monitor. I think this is a bug.

### Steps to reproduce

when I open the tool, the sidebars of the stage manager will disappear from the main monitor.

### Expected behavior

The tool will not affect the stage manager.

### Environment Information (please complete the following information)

```markdown
- macOS version:13.0
- Mac model:M1 Macbook pro13
- MonitorControl version: 4.10
- Monitor(s): main monitor
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment] 2022-06-25 18:32
This is a duplicate of #1088 

See the reason here: See the reason here: https://github.com/waydabber/BetterDisplay/issues/717

**Closed** 2022-06-25 18:32 UTC
