### ISSUE TITLE
Brightness fine. No volume control.

### ISSUE THREAD

**Issue by harryfear** [MonitorControl/MonitorControl#322] opened 2020-11-14 21:48 UTC
I can't get volume control to work at all with MonitorControl.

Brightness controls work absolutely perfectly. Magic! I'd pay $30 USD for this software.

Is the volume remuxed inside macOS or is a signal sent down the to-monitor cable?

MacBook Pro 16"
Dell 27'
USB-C connection

**Comment by Starbix** [comment] 2020-11-16 08:34
I also have a Dell 27" monitor (a U2720Q to be specific).
I'm pretty sure this monitor doesn't have a volume control at all (there's none in the menu) so MonitorControl also can't control the volume.
It'd be nice though if you could hide the volume control in this case.

**Comment by harryfear** [comment] 2020-11-16 09:58
Thanks for this reply! I have the same monitor.

I understand that MonitorControl just instructs the monitor or feed then. Thanks for this info.

For now I'm using the free eqMac workaround to enable volume keys while outputting to the Dell.

Thanks again.

PS Nice idea to disable volume functionality.

**Comment by JoniVR** [comment] 2020-11-22 14:56
Duplicate of #226

**Comment by waydabber** [comment] 2021-08-21 16:50
For displays that have problems with volume control we recommend eqMac or SoundSource. These are software solutions and do not control the display's amplifier, but still for most users these do the trick. I'll close this issue now. Thank you!

**Closed by waydabber** 2021-08-21 16:50 UTC
Labels: Monitor Issue
