### ISSUE TITLE
Application crashes when reconnecting MacBook with multi-output audio device

### ISSUE THREAD

**Issue by bellwood** [MonitorControl/MonitorControl#856] opened 2021-12-22 13:21 UTC
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

I have a 2021 M1 MacBook Pro running Monterey 12.1. 

I am driving (2) LG 32UL950-W via thunderbolt (chained)

I have each monitor and the MacBook Internal Speakers in a Multi-Output device using the Macs Audio Midi Setup.

At the end of each day, I unplug the primary screen from my MacBook and upon returning the next day, MonitorControl has crashed and I need to restart the application.

My co-worker has the same laptop and display setup and does not experience this crash, he however is not using multi-output for audio.

As a test, yesterday, I removed my multi-output before packing up and this morning MonitorControl was still running properly.

I am glad to provide additional testing or logging 

### Steps to reproduce

Create a multi-output audio device, add both displays and laptop speakers.

The application should crash upon disconnection of the displays or upon the displays being reconnected.

### Expected behavior

The application should not crash

### Environment Information (please complete the following information)

```markdown
- macOS version: 12.1 Monterey
- Mac model: 2021 M1 Macbook Pro 16"
- MonitorControl version: 4.0.2
- Monitor(s): (2) LG 32UL950-W
- Apple Silicon/M1 (yes or no): Yes
```

**Comment by waydabber** [comment] 2021-12-22 15:16
Whoa, talk about an exotic use-case. :)

**Comment by waydabber** [comment] 2021-12-22 15:28
I was trying to recreate this problem by creating a multi-output device with the MacBook Speaker, display speaker (and also with a third USB audio device) and was trying to disconnect the display, but nothing seemed to happen. It is currently unclear why this happens. It would be useful to have a crash log or some console log outputs of MonitorControl.

Also - what are the volume control options set under Keyboard and do you have "Play feedback when volume is changed" enabled under Sound in System Preferences?

I am afraid the config is so exotic (new MB Pro and daisy chained thunderbolt displays) that it's going to be super difficult to reproduce this issue anywhere but with your config. The best thing you could do is download XCode, clone the project, run te app from XCode and try to recreate the problem. The XCode debugger should tell you exactly why and where did the app crash, this could give us more insight.

**Comment by bellwood** [comment] 2021-12-22 16:17
> It would be useful to have a crash log or some console log outputs of MonitorControl.

This is yesterday's crash log for the app:

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               MonitorControl [7458]
Path:                  /Applications/MonitorControl.app/Contents/MacOS/MonitorControl
Identifier:            me.guillaumeb.MonitorControl
Version:               4.0.2 (6965)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2021-12-21 08:32:26.4115 -0500
OS Version:            macOS 12.1 (21C52)
Report Version:        12
Anonymous UUID:        998A755C-4B31-8EED-278B-002634425BBC

Sleep/Wake UUID:       EBFC3024-F6E2-449C-A443-003F685D8542

Time Awake Since Boot: 61000 seconds
Time Since Wake:       1598 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x0000000100a168d0
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [7458]

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   MonitorControl                	       0x100a168d0 0x100a0c000 + 43216
1   MonitorControl                	       0x100a1675c 0x100a0c000 + 42844
2   MonitorControl                	       0x100a5670c 0x100a0c000 + 304908
3   MonitorControl                	       0x100a565f8 0x100a0c000 + 304632
4   MonitorControl                	       0x100a5a788 0x100a0c000 + 321416
5   MonitorControl                	       0x100a54e0c 0x100a0c000 + 298508
6   libdispatch.dylib             	       0x190c4abac _dispatch_client_callout + 20
7   libdispatch.dylib             	       0x190c4e080 _dispatch_continuation_pop + 504
8   libdispatch.dylib             	       0x190c611a4 _dispatch_source_invoke + 1356
9   libdispatch.dylib             	       0x190c59000 _dispatch_main_queue_callback_4CF + 772
10  CoreFoundation                	       0x190f15f00 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
11  CoreFoundation                	       0x190ed38c0 __CFRunLoopRun + 2540
12  CoreFoundation                	       0x190ed2734 CFRunLoopRunSpecific + 600
13  HIToolbox                     	       0x199a64f68 RunCurrentEventLoopInMode + 292
14  HIToolbox                     	       0x199a64cdc ReceiveNextEventCommon + 552
15  HIToolbox                     	       0x199a64a9c _BlockUntilNextEventMatchingListInModeWithFilter + 72
16  AppKit                        	       0x193a28ce0 _DPSNextEvent + 844
17  AppKit                        	       0x193a27584 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1332
18  AppKit                        	       0x193a195a4 -[NSApplication run] + 596
19  MonitorControl                	       0x100a0e4b4 0x100a0c000 + 9396
20  libswiftObjectiveC.dylib      	       0x1a56a3acc autoreleasepool<A>(invoking:) + 64
21  MonitorControl                	       0x100a0e420 0x100a0c000 + 9248
22  dyld                          	       0x100ccd0f4 start + 520

Thread 1:: AMCP Logging Spool
0   libsystem_kernel.dylib        	       0x190dcd990 semaphore_wait_trap + 8
1   caulk                         	       0x1997d68ac caulk::mach::semaphore::wait_or_error() + 28
2   caulk                         	       0x1997b965c caulk::concurrent::details::worker_thread::run() + 56
3   caulk                         	       0x1997b927c void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*) + 96
4   libsystem_pthread.dylib       	       0x190e09240 _pthread_start + 148
5   libsystem_pthread.dylib       	       0x190e04024 thread_start + 8

Thread 2:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x190dcd954 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x190dcdd00 mach_msg + 76
2   CoreFoundation                	       0x190ed4ed8 __CFRunLoopServiceMachPort + 372
3   CoreFoundation                	       0x190ed3390 __CFRunLoopRun + 1212
4   CoreFoundation                	       0x190ed2734 CFRunLoopRunSpecific + 600
5   AppKit                        	       0x193b95c90 _NSEventThread + 196
6   libsystem_pthread.dylib       	       0x190e09240 _pthread_start + 148
7   libsystem_pthread.dylib       	       0x190e04024 thread_start + 8

Thread 3:
0   libsystem_pthread.dylib       	       0x190e04010 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	       0x190e04010 start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	       0x190e04010 start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	       0x190e04010 start_wqthread + 0

Thread 7::  Dispatch queue: MediaKeyTap Runloop
0   libsystem_kernel.dylib        	       0x190dcd954 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x190dcdd00 mach_msg + 76
2   CoreFoundation                	       0x190ed4ed8 __CFRunLoopServiceMachPort + 372
3   CoreFoundation                	       0x190ed3390 __CFRunLoopRun + 1212
4   CoreFoundation                	       0x190ed2734 CFRunLoopRunSpecific + 600
5   CoreFoundation                	       0x190f5ecc8 CFRunLoopRun + 64
6   MonitorControl                	       0x100aa42e0 0x100a0c000 + 623328
7   MonitorControl                	       0x100aa1090 0x100a0c000 + 610448
8   libdispatch.dylib             	       0x190c48e60 _dispatch_call_block_and_release + 32
9   libdispatch.dylib             	       0x190c4abac _dispatch_client_callout + 20
10  libdispatch.dylib             	       0x190c52330 _dispatch_lane_serial_drain + 672
11  libdispatch.dylib             	       0x190c52ea4 _dispatch_lane_invoke + 392
12  libdispatch.dylib             	       0x190c5d708 _dispatch_workloop_worker_thread + 656
13  libsystem_pthread.dylib       	       0x190e05304 _pthread_wqthread + 288
14  libsystem_pthread.dylib       	       0x190e04018 start_wqthread + 8

Thread 8:
0   libsystem_pthread.dylib       	       0x190e04010 start_wqthread + 0


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000103   x2: 0x0000000000000002   x3: 0x0000000100aec6d0
    x4: 0x0000000000000073   x5: 0x0000000000000073   x6: 0x0000000000000073   x7: 0x0000000000000000
    x8: 0x0000000000000000   x9: 0x0000000000000000  x10: 0x0000000000000001  x11: 0x000000007ffffffe
   x12: 0x0000000000000001  x13: 0x000000007ffffffe  x14: 0x00000000c408a800  x15: 0x000000000008a800
   x16: 0x0000000190e1e3d4  x17: 0x00000001eb92e618  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x0000000000000001  x21: 0x0000000000000004  x22: 0x0000000000000001  x23: 0x0000000000000000
   x24: 0x00006000006b7960  x25: 0x0000000000000000  x26: 0x0000000000000002  x27: 0x0000000000000001
   x28: 0x00006000039f0f00   fp: 0x000000016f3f1fa0   lr: 0x3357800100a1675c
    sp: 0x000000016f3f1f10   pc: 0x0000000100a168d0 cpsr: 0x60001000
   far: 0x0000000108110000  esr: 0xf2000001 (Breakpoint) brk 1

Binary Images:
       0x100a0c000 -        0x100ad7fff me.guillaumeb.MonitorControl (4.0.2) <ba522289-6115-3fa9-a291-02cc39d9f07c> /Applications/MonitorControl.app/Contents/MacOS/MonitorControl
       0x190c47000 -        0x190c8dfff libdispatch.dylib (*) <3a9e9a1e-72b6-3f66-aa17-d955384c1a39> /usr/lib/system/libdispatch.dylib
       0x190e50000 -        0x191393fff com.apple.CoreFoundation (6.9) <f5ea9592-4ef9-3d35-b23d-5c21283acc52> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x199a32000 -        0x199d61fff com.apple.HIToolbox (2.1.1) <01b981b8-a2d8-374d-9a0e-c4ac8c1009da> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
       0x1939e7000 -        0x19489afff com.apple.AppKit (6.9) <a8bbc643-113d-310f-96b6-77a973bf2dba> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x1a56a2000 -        0x1a56a4fff libswiftObjectiveC.dylib (*) <2a19a29d-2fa2-3932-9e9f-e34681fb4638> /usr/lib/swift/libswiftObjectiveC.dylib
       0x100cc8000 -        0x100d27fff dyld (*) <7e92b284-4b90-3b68-b31a-3ddc4c0e8d40> /usr/lib/dyld
       0x190dcc000 -        0x190e01fff libsystem_kernel.dylib (*) <c8b3081a-5081-3a99-bbe3-01413de444c6> /usr/lib/system/libsystem_kernel.dylib
       0x1997b7000 -        0x1997defff com.apple.audio.caulk (1.0) <37a561f9-46f0-37fe-811b-894385645aed> /System/Library/PrivateFrameworks/caulk.framework/Versions/A/caulk
       0x190e02000 -        0x190e0efff libsystem_pthread.dylib (*) <ed328b18-eeef-3b15-8858-798b19b0c2cd> /usr/lib/system/libsystem_pthread.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)
Writable regions: Total=1.9G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.9G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               512K        4 
Activity Tracing                   256K        1 
CG image                           224K        6 
ColorSync                          512K       24 
CoreAnimation                      112K        7 
CoreGraphics                        64K        4 
Foundation                          16K        1 
Kernel Alloc Once                   32K        1 
MALLOC                           318.5M       66 
MALLOC guard page                  288K       15 
MALLOC_MEDIUM (reserved)           1.2G       10         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
SQLite page cache                   64K        1 
STACK GUARD                       56.1M        9 
Stack                             12.2M        9 
VM_ALLOCATE                        1.0G        9 
__AUTH                            2402K      256 
__AUTH_CONST                      17.9M      435 
__DATA                            11.8M      421 
__DATA_CONST                      15.2M      441 
__DATA_DIRTY                      1529K      168 
__FONT_DATA                          4K        1 
__LINKEDIT                       576.0M        5 
__OBJC_CONST                      2563K      208 
__OBJC_RO                         82.0M        1 
__OBJC_RW                         3104K        1 
__TEXT                           425.4M      458 
__UNICODE                          588K        1 
dyld private memory               1024K        1 
libnetwork                         128K        8 
mapped file                      139.2M       22 
shared memory                      848K       12 
===========                     =======  ======= 
TOTAL                              4.2G     2607 
TOTAL, minus reserved VM space     2.6G     2607 



-----------
Full Report
-----------

{"app_name":"MonitorControl","timestamp":"2021-12-21 08:32:28.00 -0500","app_version":"4.0.2","slice_uuid":"ba522289-6115-3fa9-a291-02cc39d9f07c","build_version":"6965","platform":1,"bundleID":"me.guillaumeb.MonitorControl","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.1 (21C52)","incident_id":"C9495D12-02B0-43D1-AD0A-B59BFCBD5DFF","name":"MonitorControl"}
{
  "uptime" : 61000,
  "procLaunch" : "2021-12-20 08:18:19.6425 -0500",
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,1",
  "procStartAbsTime" : 644627051893,
  "coalitionID" : 2552,
  "osVersion" : {
    "train" : "macOS 12.1",
    "build" : "21C52",
    "releaseType" : "User"
  },
  "captureTime" : "2021-12-21 08:32:26.4115 -0500",
  "incident" : "C9495D12-02B0-43D1-AD0A-B59BFCBD5DFF",
  "bug_type" : "309",
  "pid" : 7458,
  "procExitAbsTime" : 1479554355946,
  "translated" : false,
  "cpuType" : "ARM-64",
  "procName" : "MonitorControl",
  "procPath" : "\/Applications\/MonitorControl.app\/Contents\/MacOS\/MonitorControl",
  "bundleInfo" : {"CFBundleShortVersionString":"4.0.2","CFBundleVersion":"6965","CFBundleIdentifier":"me.guillaumeb.MonitorControl"},
  "storeInfo" : {"deviceIdentifierForVendor":"7B762C69-8224-5089-AE2C-5561F7309CFF","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "me.guillaumeb.MonitorControl",
  "crashReporterKey" : "998A755C-4B31-8EED-278B-002634425BBC",
  "wakeTime" : 1598,
  "sleepWakeUUID" : "EBFC3024-F6E2-449C-A443-003F685D8542",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x0000000100a168d0","rawCodes":[1,4305545424],"type":"EXC_BREAKPOINT","signal":"SIGTRAP"},
  "termination" : {"flags":0,"code":5,"namespace":"SIGNAL","indicator":"Trace\/BPT trap: 5","byProc":"exc handler","byPid":7458},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":346842,"threadState":{"x":[{"value":0},{"value":259},{"value":2},{"value":4306421456},{"value":115},{"value":115},{"value":115},{"value":0},{"value":0},{"value":0},{"value":1},{"value":2147483646},{"value":1},{"value":2147483646},{"value":3288901632},{"value":567296},{"value":6725690324,"symbolLocation":0,"symbol":"_os_nospin_lock_unlock"},{"value":8247240216},{"value":0},{"value":0},{"value":1},{"value":4},{"value":1},{"value":0},{"value":105553123309920},{"value":0},{"value":2},{"value":1},{"value":105553177022208}],"flavor":"ARM_THREAD_STATE64","lr":{"value":3699566360702052188},"cpsr":{"value":1610616832},"fp":{"value":6161375136},"sp":{"value":6161374992},"esr":{"value":4060086273,"description":"(Breakpoint) brk 1"},"pc":{"value":4305545424,"matchesCrashFrame":1},"far":{"value":4430299136}},"queue":"com.apple.main-thread","frames":[{"imageOffset":43216,"imageIndex":0},{"imageOffset":42844,"imageIndex":0},{"imageOffset":304908,"imageIndex":0},{"imageOffset":304632,"imageIndex":0},{"imageOffset":321416,"imageIndex":0},{"imageOffset":298508,"imageIndex":0},{"imageOffset":15276,"symbol":"_dispatch_client_callout","symbolLocation":20,"imageIndex":1},{"imageOffset":28800,"symbol":"_dispatch_continuation_pop","symbolLocation":504,"imageIndex":1},{"imageOffset":106916,"symbol":"_dispatch_source_invoke","symbolLocation":1356,"imageIndex":1},{"imageOffset":73728,"symbol":"_dispatch_main_queue_callback_4CF","symbolLocation":772,"imageIndex":1},{"imageOffset":810752,"symbol":"__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__","symbolLocation":16,"imageIndex":2},{"imageOffset":538816,"symbol":"__CFRunLoopRun","symbolLocation":2540,"imageIndex":2},{"imageOffset":534324,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":2},{"imageOffset":208744,"symbol":"RunCurrentEventLoopInMode","symbolLocation":292,"imageIndex":3},{"imageOffset":208092,"symbol":"ReceiveNextEventCommon","symbolLocation":552,"imageIndex":3},{"imageOffset":207516,"symbol":"_BlockUntilNextEventMatchingListInModeWithFilter","symbolLocation":72,"imageIndex":3},{"imageOffset":269536,"symbol":"_DPSNextEvent","symbolLocation":844,"imageIndex":4},{"imageOffset":263556,"symbol":"-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]","symbolLocation":1332,"imageIndex":4},{"imageOffset":206244,"symbol":"-[NSApplication run]","symbolLocation":596,"imageIndex":4},{"imageOffset":9396,"imageIndex":0},{"imageOffset":6860,"symbol":"autoreleasepool<A>(invoking:)","symbolLocation":64,"imageIndex":5},{"imageOffset":9248,"imageIndex":0},{"imageOffset":20724,"symbol":"start","symbolLocation":520,"imageIndex":6}]},{"id":346869,"name":"AMCP Logging Spool","frames":[{"imageOffset":6544,"symbol":"semaphore_wait_trap","symbolLocation":8,"imageIndex":7},{"imageOffset":129196,"symbol":"caulk::mach::semaphore::wait_or_error()","symbolLocation":28,"imageIndex":8},{"imageOffset":9820,"symbol":"caulk::concurrent::details::worker_thread::run()","symbolLocation":56,"imageIndex":8},{"imageOffset":8828,"symbol":"void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*)","symbolLocation":96,"imageIndex":8},{"imageOffset":29248,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":9},{"imageOffset":8228,"symbol":"thread_start","symbolLocation":8,"imageIndex":9}]},{"id":346890,"name":"com.apple.NSEventThread","frames":[{"imageOffset":6484,"symbol":"mach_msg_trap","symbolLocation":8,"imageIndex":7},{"imageOffset":7424,"symbol":"mach_msg","symbolLocation":76,"imageIndex":7},{"imageOffset":544472,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":372,"imageIndex":2},{"imageOffset":537488,"symbol":"__CFRunLoopRun","symbolLocation":1212,"imageIndex":2},{"imageOffset":534324,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":2},{"imageOffset":1764496,"symbol":"_NSEventThread","symbolLocation":196,"imageIndex":4},{"imageOffset":29248,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":9},{"imageOffset":8228,"symbol":"thread_start","symbolLocation":8,"imageIndex":9}]},{"id":729108,"frames":[{"imageOffset":8208,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":9}]},{"id":734487,"frames":[{"imageOffset":8208,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":9}]},{"id":734507,"frames":[{"imageOffset":8208,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":9}]},{"id":734508,"frames":[{"imageOffset":8208,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":9}]},{"id":734816,"queue":"MediaKeyTap Runloop","frames":[{"imageOffset":6484,"symbol":"mach_msg_trap","symbolLocation":8,"imageIndex":7},{"imageOffset":7424,"symbol":"mach_msg","symbolLocation":76,"imageIndex":7},{"imageOffset":544472,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":372,"imageIndex":2},{"imageOffset":537488,"symbol":"__CFRunLoopRun","symbolLocation":1212,"imageIndex":2},{"imageOffset":534324,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":2},{"imageOffset":1109192,"symbol":"CFRunLoopRun","symbolLocation":64,"imageIndex":2},{"imageOffset":623328,"imageIndex":0},{"imageOffset":610448,"imageIndex":0},{"imageOffset":7776,"symbol":"_dispatch_call_block_and_release","symbolLocation":32,"imageIndex":1},{"imageOffset":15276,"symbol":"_dispatch_client_callout","symbolLocation":20,"imageIndex":1},{"imageOffset":45872,"symbol":"_dispatch_lane_serial_drain","symbolLocation":672,"imageIndex":1},{"imageOffset":48804,"symbol":"_dispatch_lane_invoke","symbolLocation":392,"imageIndex":1},{"imageOffset":91912,"symbol":"_dispatch_workloop_worker_thread","symbolLocation":656,"imageIndex":1},{"imageOffset":13060,"symbol":"_pthread_wqthread","symbolLocation":288,"imageIndex":9},{"imageOffset":8216,"symbol":"start_wqthread","symbolLocation":8,"imageIndex":9}]},{"id":734818,"frames":[{"imageOffset":8208,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":9}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4305502208,
    "CFBundleShortVersionString" : "4.0.2",
    "CFBundleIdentifier" : "me.guillaumeb.MonitorControl",
    "size" : 835584,
    "uuid" : "ba522289-6115-3fa9-a291-02cc39d9f07c",
    "path" : "\/Applications\/MonitorControl.app\/Contents\/MacOS\/MonitorControl",
    "name" : "MonitorControl",
    "CFBundleVersion" : "6965"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6723760128,
    "size" : 290816,
    "uuid" : "3a9e9a1e-72b6-3f66-aa17-d955384c1a39",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6725894144,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5521408,
    "uuid" : "f5ea9592-4ef9-3d35-b23d-5c21283acc52",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1856.105"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6872571904,
    "CFBundleShortVersionString" : "2.1.1",
    "CFBundleIdentifier" : "com.apple.HIToolbox",
    "size" : 3342336,
    "uuid" : "01b981b8-a2d8-374d-9a0e-c4ac8c1009da",
    "path" : "\/System\/Library\/Frameworks\/Carbon.framework\/Versions\/A\/Frameworks\/HIToolbox.framework\/Versions\/A\/HIToolbox",
    "name" : "HIToolbox"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6771601408,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15417344,
    "uuid" : "a8bbc643-113d-310f-96b6-77a973bf2dba",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2113.20.111"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7070162944,
    "size" : 12288,
    "uuid" : "2a19a29d-2fa2-3932-9e9f-e34681fb4638",
    "path" : "\/usr\/lib\/swift\/libswiftObjectiveC.dylib",
    "name" : "libswiftObjectiveC.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4308369408,
    "size" : 393216,
    "uuid" : "7e92b284-4b90-3b68-b31a-3ddc4c0e8d40",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6725353472,
    "size" : 221184,
    "uuid" : "c8b3081a-5081-3a99-bbe3-01413de444c6",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6869970944,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.apple.audio.caulk",
    "size" : 163840,
    "uuid" : "37a561f9-46f0-37fe-811b-894385645aed",
    "path" : "\/System\/Library\/PrivateFrameworks\/caulk.framework\/Versions\/A\/caulk",
    "name" : "caulk"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6725574656,
    "size" : 53248,
    "uuid" : "ed328b18-eeef-3b15-8858-798b19b0c2cd",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  }
],
  "sharedCache" : {
  "base" : 6722404352,
  "size" : 3089596416,
  "uuid" : "66c33c62-48a9-31e5-b8b5-7a71c9760d07"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)\nWritable regions: Total=1.9G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.9G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               512K        4 \nActivity Tracing                   256K        1 \nCG image                           224K        6 \nColorSync                          512K       24 \nCoreAnimation                      112K        7 \nCoreGraphics                        64K        4 \nFoundation                          16K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           318.5M       66 \nMALLOC guard page                  288K       15 \nMALLOC_MEDIUM (reserved)           1.2G       10         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nSQLite page cache                   64K        1 \nSTACK GUARD                       56.1M        9 \nStack                             12.2M        9 \nVM_ALLOCATE                        1.0G        9 \n__AUTH                            2402K      256 \n__AUTH_CONST                      17.9M      435 \n__DATA                            11.8M      421 \n__DATA_CONST                      15.2M      441 \n__DATA_DIRTY                      1529K      168 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       576.0M        5 \n__OBJC_CONST                      2563K      208 \n__OBJC_RO                         82.0M        1 \n__OBJC_RW                         3104K        1 \n__TEXT                           425.4M      458 \n__UNICODE                          588K        1 \ndyld private memory               1024K        1 \nlibnetwork                         128K        8 \nmapped file                      139.2M       22 \nshared memory                      848K       12 \n===========                     =======  ======= \nTOTAL                              4.2G     2607 \nTOTAL, minus reserved VM space     2.6G     2607 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    },
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "6103050cbfe6dc472e1c982a"
      },
      "deploymentId" : 240000066
    },
    {
      "rolloutId" : "602ad4dac86151000cf27e46",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "61a80a438feb033580c2778b"
      },
      "deploymentId" : 240000290
    },
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {

      },
      "deploymentId" : 240000185
    },
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000090
    },
    {
      "rolloutId" : "601d9415f79519000ccd4b69",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "6194416f2171a2330e561f05"
      },
      "deploymentId" : 240000355
    }
  ],
  "experiments" : [

  ]
}
}

> what are the volume control options set under Keyboard
Volume control: Standard keyboard volume and mute keys
Screen to control: Change volumes for all screens
OSD Scale: Checked

> do you have "Play feedback when volume is changed" enabled under Sound in System Preferences
I do not

> The best thing you could do is download XCode, clone the project, run te app from XCode and try to recreate the problem. The XCode debugger should tell you exactly why and where did the app crash, this could give us more insight.

I am absolutely glad to figure out how todo this if the above crash report isn't helpful. I can provide a few others if needed.

Thank you!

**Comment by waydabber** [comment] 2021-12-22 18:26
To be honest, based on this changelog I have no idea what's wrong except that the app indeed crashed. :) But it seems that almost half an hour passed since last wake so it does not crash upon wake immediately.

I recommend you building and running the app in XCode and see why and how it crashes. For some audio operations MonitorControl uses a 3rd party package called SimplyCoreAudio, it is possible that the problem lies there - but in the crashlog I don't see any obvious inditcation that this is the case or that the problem is audio related at all.

If you do not use the aggregate device, the crash does not happen as well? If so, then what happens if you do not daisy chain the displays or connect each of the displays directly to the MBP?

**Comment by bellwood** [comment] 2021-12-22 18:45
Will do some testing and work to get you further details. Thanks =)

**Comment by waydabber** [comment] 2022-01-02 08:43
Hey Brian, let me know if you have any update on this as I still can't seem to reproduce the issue. Thank you!

**Comment by waydabber** [comment] 2022-01-04 17:23
Hi, I'll close this issue for now but we'll reopen it once we have more info and can progress with it. Thank you!

**Closed by waydabber** 2022-01-04 17:23 UTC
Labels: Type: Bug, Status: Feedback needed from issue reporter, Investigating
