### ISSUE TITLE
Still does not work to control brightness of Macbook Pro built-in display

### ISSUE THREAD

**Issue by starmandeluxe** [MonitorControl/MonitorControl#535] opened 2021-08-24 03:01 UTC
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

MonitorControl only allows brightness slider on an external monitor, not the Macbook Pro's built-in monitor.

### Steps to reproduce

1. Go to the brightness icon in the system top bar
2. Click on the brightness icon
3. Cannot control brightness on the Macbook's built-in monitor

### Expected behavior

Expected behavior
A slider to be able to control the Macbook's monitor brightness (see thread here: https://forums.macrumors.com/threads/menu-bar-brightness-slider.2105286/)

### Environment Information (please complete the following information)

```markdown
- macOS version: MacOS Big Sur 11.5.2
- Mac model: Macbook Pro 2017
- MonitorControl version: 3.0.0
- Monitor(s): Built-in Macbook Pro display
- Apple Silicon/M1 (yes or no): no
```

**Comment by waydabber** [comment] 2021-08-24 07:38
Hi, this is not a bug but intentional, since the built-in display already has a dedicated slider in Control Center provided by the OS. Nevertheless there is a plan to add an option to show the slider for the internal display as well (this needs a bit of code refactoring but can be done):

https://github.com/MonitorControl/MonitorControl/issues/198

Since this issue is a duplicate of that request, I'll close this one - please feel free to comment in the other thread! Thank you!

**Closed by waydabber** 2021-08-24 07:38 UTC
Labels: Duplicate, Feature Request

**Comment by starmandeluxe** [comment] 2021-08-25 16:59
The main advantage of using this tool is to avoid having to control the brightness using Touch Controls. This feature is needed.

**Comment by waydabber** [comment] 2021-09-02 21:00
Yes, but you already have a non touch based control option in the OS itself. Or am I missing something? :)

<img width="346" alt="Screen Shot 2021-09-02 at 23 00 12" src="https://user-images.githubusercontent.com/37590873/131915419-0ff94c65-790f-453e-badd-dc0345100a76.png">

**Comment by waydabber** [comment] 2021-09-03 21:49
Hi! There is a build in the following isse with slider for built-in screens (and also proper support for Apple displays): https://github.com/MonitorControl/MonitorControl/issues/539

**Comment by starmandeluxe** [comment] 2021-09-22 05:04
> Yes, but you already have a non touch based control option in the OS itself. Or am I missing something? :)
> 
> <img alt="Screen Shot 2021-09-02 at 23 00 12" width="346" src="https://user-images.githubusercontent.com/37590873/131915419-0ff94c65-790f-453e-badd-dc0345100a76.png">

Because when I originally reported the first issue, it didn't exist. See the thread I referenced above.

**Comment by waydabber** [comment] 2021-09-22 05:26
Yep. The main thing is that now you can have sliders here and there as well. :)
