### ISSUE TITLE
dell up2715k in 5k mode

### ISSUE THREAD

**Issue by mrmggo** [MonitorControl/MonitorControl#283] opened 2020-08-29 13:56 UTC
Can you increase the brightness control of dell up2715k in 5k mode?
At present, the brightness can be perfectly controlled in 4k mode, but it cannot be controlled in 5k mode.
In windows system, the brightness control in 5k mode can be realized by installing the official dell software.

Thank you

**Comment by chongkong** [comment] 2020-09-14 21:02
That's strange. I'm using up2715k in 5k and I'm having full control over display brightness with MonitorControl. Using Catalina 10.15.6 and the latest dell driver in mac mini 2018.

**Comment by JoniVR** [comment] 2020-09-19 12:29
Could perhaps be a bandwidth issue then? Try the Monitor troubleshooting guide:
https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting

**Comment by mrmggo** [comment] 2020-09-21 02:31
Thanks Reply
I have updated to 2.1.0 and still cannot control my 2715k in 5k
I installed Dell Display Manager Application under windows, which can control the brightness and volume of the display very well, and it works in 5k mode
Can't succeed under macos, try to use ddcctl still can't
My hardware is imac2019, and the graphics card is vega48. The display is connected to the display through 2 dp cables of Thunderbolt 3 output. The macos system version is 10.15.
I tried to find the macos version of Dell Display Manager Application on the Dell official website, but couldn't find it.

**Comment by Rastafabisch** [comment] 2020-12-02 01:05
[This](https://github.com/kfix/ddcctl/issues/51) is related.

**Comment by waydabber** [comment] 2021-08-21 16:52
This is a duplicate of https://github.com/kfix/ddcctl/issues/51 so I'll close this one. Thank you!

**Comment by waydabber** [comment] 2021-08-21 16:56
Whops, this is a legit issue, sorry for closing it. :)

We'd need somebody with a access to 5k display with dual DP and an Intel mac and the proper skills to help figuring this out. I think this issue should be raised as an issue at https://github.com/reitermarkus/DDC.swift/issues.

You can try version 3.0.0 though as it has some tweaks in display detection logic, but I honestly don't think that it will work. Let me know if this issue still persists in the current version! Thank you!

**Comment by waydabber** [comment] 2021-08-25 16:32
I'll close this issue for now but please feel free to comment if there is anything we can do. If the issue persists, we can reopen this issue! Thank you!

**Closed by waydabber** 2021-08-25 16:32 UTC
Labels: Monitor Issue, Feedback/info required!
