### ISSUE TITLE
Custom shortcuts (for external keyboard users)

### ISSUE THREAD

**Issue by bishshoy** [MonitorControl/MonitorControl#249] opened 2020-07-08 10:27 UTC
I use an external keyboard, and I am unable to use F1 or F2 to change the brightness of the LG Ultrafine 4k monitor. The sliders work perfectly. I was unable to find a setting for assigning a custom keyboard shortcut to the application. Is there any default shortcut already assigned? I can remap the defaults using BetterTouchTool then. I was unable to find any info on the default shortcuts in the readme.

**Comment by bishshoy** [comment] 2020-07-08 10:43
Ok. I found something. In BetterTouchTool, I can just set a shortcut for "Brightness Up/Down" and it works. It also works for "Volume Up/Down", but I wasn't able to find anything related to Contrast. So having a shortcut in the app itself to assign custom keyboard shortcuts to contrast would be nice.

**Comment by JoniVR** [comment] 2020-07-09 19:25
duplicate of #118

**Closed by JoniVR** 2020-07-09 19:25 UTC
Labels: Type: Feature Request
