### ISSUE TITLE
LG 38GL950G has partial range support, highest volume mutes

### ISSUE THREAD

**Issue by Hexxeh** [MonitorControl/MonitorControl#335] opened 2020-11-26 14:00 UTC
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the Monitor Troubleshooting wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [x] I have updated MonitorControl to the latest version

**Describe the issue**
LG 38GL950G connected via USB-C to HDMI adaptor to 2019 Macbook Pro 15" can control volume and brightness, but has several quirks

Volume settings behave incorrectly at both ends of the scale:

- OSD shows 5/100 at level 1 brightness on OSX overlay, but goes to 25/100 at level 0 on OSX overlay
- Highest volume setting on OSX overlay turns off sound completely `I: VCP control #98 (0x62) = current: 255, max: 255`

Brightness settings behave incorrectly for much of the scale:

- OSD turns off entirely and doesn't show changes made by OSX, just shows `/` character when brightness set by OSX
- OSX overlay brightness levels 0-4 show no change in brightness. `I: VCP control #16 (0x10) = current: 60, max: 194` values stick at 60 even when settings change lower than 4.
- Highest OSX overlay brightness setting is approximately 50% of the monitors max brightness. `I: VCP control #16 (0x10) = current: 194, max: 194`

Not sure if these are just quirks of my monitor that can't be fixed, since in some cases the range reports correctly. If so, maybe I can help implement quirks support to handle these?

**Expected behavior**
Brightness and volume control same full range possible via OSD.

**Screenshots**

**Additional context**

**Environment Information (please complete the following information):**
 - macOS version: 10.15.7
 - MonitorControl version: 2.1.0 Build 721
 - Monitor(s): LG 38GL950G
 - Mac model: Macbook Pro 15" Late 2019
 - Monitor Cable(s)/Connection(s): HDMI via USB-C

**Comment by Hexxeh** [comment] 2020-11-27 09:52
Noticed for brightness that setting `/ddcctl -d 1 -b 255` does result in a brighter image than full brightness via MonitorControl, which I'm guessing is stopping at the reported 194 max.

**Comment by waydabber** [comment] 2021-08-19 07:30
It would be great to have an advanced preferences option where DDC min. and max. values could be overridden. I will assign this task to myself, but I don't know when will I be able to actually implement it. :)

**Comment by waydabber** [comment] 2021-08-19 07:36
Hi, since this is a duplicate of the issue below, I'll close this issue now - please follow developments here:

https://github.com/MonitorControl/MonitorControl/issues/310

**Closed by waydabber** 2021-08-19 07:36 UTC
Labels: Monitor Issue
