### ISSUE TITLE
LG Ultrafine 5K brightness change override by system setting.

### ISSUE THREAD

**Issue by joechen1105** [MonitorControl/MonitorControl#472] opened 2021-07-25 03:14 UTC
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [x] I have updated MonitorControl to the latest version

**Describe the bug**
Monitor control got override by system brightness setting.

**To Reproduce**
-adjust brightness through Monitor Control
-brightness changes during adjustment
-brightness changed back to original setting

**Expected behavior**

**Screenshots**

**Additional context**

**Environment Information (please complete the following information):**

- macOS version: 11.4
- Mac model: MacBook Pro 15 2018
- MonitorControl version: 2.1
- Monitor(s):LG Ultrafine 5K
- Apple Silicon/M1 (yes or no):no

**Comment by waydabber** [comment] 2021-08-20 17:01
This problem lies in the fact that the LG Ultrafine 5K should not be controlled via DDC but via DisplayServices as this display knows Apple's USB MCCS protocol. In case of DDC control macOS is not aware of changes and will revert any change whenever it feels it needs to change brightness for whatever reason.

I plan to add this functionality in an upcoming version. The issue is tracked here: 

https://github.com/MonitorControl/MonitorControl/issues/364

I will close this issue now, but please if you have anything to add let me know in that thread + also if the issue is updated, we'll need you as a tester (if you have to time) to test the update on this display. Thank you!

**Closed by waydabber** 2021-08-20 17:01 UTC
Labels: Bug, Monitor Issue

**Comment by waydabber** [comment] 2021-09-03 21:53
For those with Apple displays, there is a link to a test build with proper support here: https://github.com/MonitorControl/MonitorControl/issues/539
