### ISSUE TITLE
AOC2790 not supported with MacBook Air M1 over USB-C Hub

### ISSUE THREAD

**Issue by kasti0** [MonitorControl/MonitorControl#385] opened 2021-02-03 15:39 UTC
the monitor was supported on a laptop that was set up as a hackintosh and had direct HDMI connection. Are USB-C hubs not supported? the app detects the monitor but just display "no supported monitor connected"

**Comment by joeyboey** [comment] 2021-02-04 13:03
Should be:
Duplicate of #323

**Closed** 2021-02-05 16:53 UTC

**Comment by kasti0** [comment] 2021-02-05 17:03
it should be a duplicate of that error.
However there's something else going on. When MonitorCOntrol is running I'm not even able to change the display brightness of the internal screen. I only can change between highest setting and one below.
