### ISSUE TITLE
MacBook Pro2018 connected to Dell U2720QM monitor cannot adjust the volume of the monitor

### ISSUE THREAD

**Issue by he675724590** [MonitorControl/MonitorControl#399] opened 2021-03-02 02:20 UTC
Press the shortcut key to display the volume adjustment prompt box, but the volume has not changed in fact

System 10.15.7

**Comment by TTappDev** [comment] 2021-03-18 19:48
Reproduced with version 2.1.0 (Build 721)

**Comment by kasparv** [comment] 2021-03-18 19:53
Reproduced on MacBook Air (Retina, 13-inch, 2020) with Catalina 10.15.7 (19H524), MonitorControl Version 2.1.0 (Build 721)

**Comment by TheUKDave** [comment] 2021-04-27 07:22
Also an issue with my U2720Q, connected over USB-C to my 2020 MBP16, Catalina 10.15.7, MonitorControl 2.1.0

Both brightness and volume are greyed in the tray icon, but sliders are movable (but do nothing).  Keyboard shortcuts for volume make the MacOS speaker icon appear and make the 'blip' noises, but volume is unaffected - even muting seems to show it muted, but sound is still heard always at the same original volume.

Is it a monitor incompatibility? is it due to using USB-C?

**Comment by TheUKDave** [comment] 2021-05-10 07:10
@nvcken No I didn't, using eqmac instead now, which works.

**Comment by nvcken** [comment] 2021-05-17 11:24
ok thx, btw @TheUKDave can't use microphone when plus in headphone into monitor 3.5mm sound port, is it right?

**Comment by waydabber** [comment] 2021-08-21 12:38
Hey all,

if brightness control works but volume control does not, then it is probably not a communications issue but the display itself does not support properly the audioSpeakerVolume DDC command. Unfortunatelly there is no much to do about that, a software solution could be instead (like eqMac or SoundSource).

Also, you could try ddctl or m1ddc to see if that works to double check that indeed the problem lies with the Display:

https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting

I'll close this issue now but feel free to let me know if there is anything else I can help with or you want to try to debug one of these displays.

Thank you!

**Closed by waydabber** 2021-08-21 12:38 UTC
Labels: Monitor Issue
