### ISSUE TITLE
Volume up/down keys don't change monitor (DELL U3419W) volume on latest updates

### ISSUE THREAD

**Issue by fent** [MonitorControl/MonitorControl#479] opened 2021-07-27 07:41 UTC
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [x] I have updated MonitorControl to the latest version

**Describe the bug**
Volume up/down keys don't change the volume of the monitor. But, clicking on the MonitorControl icon and adjusting the volume there does change it.

This happens with the latest 2 updates v2.2.0 and v3.0.0-beta1. The issue is not present when downgrading to v2.1.0

**To Reproduce**

1. Download one of the latest 2 updates from the releases page
2. Install
3. Press volume up/down keys and check if the volume on your monitor changes. Easier to test by playing music or video in the background as you do this, and to lower the volume all the way down to mute to be certain.

**Expected behavior**
Expected volume of the monitor to be adjusted

**Screenshots**
![image](https://user-images.githubusercontent.com/933490/127115224-41a03077-d181-4a91-85ad-403358cb75f4.png)

**Environment Information (please complete the following information):**

- macOS version: Big Sur 11.5
- Mac model: mbp 13 inch mid 2014
- MonitorControl version: v2.2.0 and v3.0.0-beta1
- Monitor(s): DELL U3419W
- Apple Silicon/M1 (yes or no): no

**Comment by jmtakahashi** [comment] 2021-07-27 14:29
Can confirm this bug.  Same on my early 2015 macbook pro 13" connected to a LG WQHD monitor.
- Monitor Control v. 2.2.0
- OS Big Sur 11.5
Haven't tried to downgrade the Monitor Control app, but did just install the Big Sur 11.5 update and things stopped working.  My volume and brightness buttons work (display the native osd) HOWEVER the buttons do not affect my monitor's brightness or volume.  Using the sliders in the app (menu bar) DO work and control my volume/brightness correctly.

**Comment by JoniVR** [comment] 2021-07-27 15:58
Duplicate of #478

**Closed by JoniVR** 2021-07-27 15:58 UTC
Labels: Type: Bug
