### ISSUE TITLE
Customizable app icon

### ISSUE THREAD

**Issue by big610** [MonitorControl/MonitorControl#632] opened 2021-09-30 21:49 UTC
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

Workable

### Describe the solution you'd like

Line Graph Numbered Brightness/Volume, Return to Default, Colored Icon.

Different monitors begin defaulted at different positions for both Brightness & Volume.
For accuracy tuning, to precise spots, a Line Graph & Numbered. Control Ability to Default to return to original position.
Example: Connected to Manufacturer A, then Connected to Manufacturer B, results in two different Brightness/Volume settings position spots.
Could you explain in your words why each monitor has a different default beginning?

Menu Bar Icon Color from Black to a colored Icon. Your choice of color from your default blue or pink to match your Icon. Easier to distinguish in the Menu Bar from Apple's all Black Icons.

### Describe alternatives you've considered

Above

**Comment by waydabber** [comment] 2021-10-01 05:33
Hi big610,

The new [version 4.0.0](https://github.com/MonitorControl/MonitorControl/releases/tag/v4.0.0-beta1) has an option to enable percentages and also tick marks. This I think should cover the request about precise spots.

![Uploading Screen Shot 2021-10-01 at 7.26.13.png…]()

Regarding the defaults, I don't think I fully understand what you mean. 3.x.x read the display upon startup so the default values came directly from the display. The new 4.0.0 version has an option to decide how the app should behave upon startup:

<img width="803" alt="Screen Shot 2021-10-01 at 7 28 26" src="https://user-images.githubusercontent.com/37590873/135570115-1517d6ee-a101-4e02-b40b-3753116088f5.png">

Also 4.0.0 better distinguishes and does not conflate different displays connected to the same port on M1 machines (as this was a problem with 3.x.x) if that is what you meant by the request.

Regarding the colored icon, I am not sure about that, as it would deviate too much from the UI recommendations of macOS - but it would be possible to add an option to set custom icons and if a user wants colored icon, that we he could have it.

**Comment by big610** [comment] 2021-10-01 05:54
I've checked two different manufacturer displays with 4.0.0-beta1, resulting in the slider remaining the same.
What changed were the Default positions.

![4 0 0-beta1](https://user-images.githubusercontent.com/35133409/135572330-0f2eae00-0dc3-494d-a447-1aca02ae380f.png)
Answer to Defaults more defined: 
Example: to the supplied ScreenShot with no percentages I would call this Default 100% & 20%.
Version 3 for one monitor had both Default Virgin at 70% & & 70%. 
The percentages I am stating are guesses what they would display with your above ScreenShots.

Colored Icon:
All developers explain to me the UI recommendations for Apple. So yes they way around Apple, is have it in Settings to add Color to Menu Bar Icon.

**Comment by waydabber** [comment] 2021-10-01 07:39
Hi @big610 

If with v3 you had 70%/70% as default, then it means that your mac or display were not able to read the settings from the display as it is probably incompatible with DDC read (some displays have this issue), as v3 always tried to read settings upon startup. Version 4 works a bit differently - when is started for the first time or a display is attached the first time, it will apply a default value of 100% for brightness and contrast (instead of the previous 70% - to prevent unexplained dimming especially in software mode at first start) and 12,5% for volume (this was intentionally changed from 70% as that was too loud for some as default value). These are however not applied to the display during startup (unless `Apply last saved values to display` is enabled), only the first time the user attempts to change these values. This is to prevent issues at startup with displays that behave badly when they receive DDC commands and to give the user has the ability to safely navigate to the setting which disables DDC and forces software mode. You can enable `Attempt to read display settings` to make MonitorControl read settings from the display itself upon startup.

I see that you are use an older macOS version. Regarding colored icons I was thinking about an option ad App Menu / Menu Icon titled `Choose alternate icon` and a dropdown list where the user could choose an alternate [SF Symbol](https://developer.apple.com/sf-symbols/) and even set the color preferences for it. The problem is that SF Icons work with Big Sur minimum and the multicolor versions are supported only on Monterey. So you would benefit from this only if you could upgrade.

**Comment by JoniVR** [comment] 2021-10-01 16:45
I'd argue against custom menu icons for multiple reasons:

* No other apps do it, as it's not the standard for the platform (see HIG).
* The menu bar icon in a way defines the identity of the application.
* You'd have to support light/dark mode icons (maybe not important for everyone, but I can guarantee that if we were to support it, the next feature request will be icons for light/dark mode)
* It's another setting which adds little value to most users, and is not part of the core functionality, we can't keep adding infinite settings.
* It's yet another piece of code to maintain that very well might break in every single macOS update. This is especially true when we do custom stuff like this that isn't intended to be done.

**Comment by waydabber** [comment] 2021-10-01 17:58
Hi @JoniVR, all right, let's shelve this feature then, I agree that platform consistency is important.

@big610, don't despair, luckily MonitorControl is super customizable as the source code is freely available so you can easily change it in any way you'd like. If you are on macOS 10, then you can simply change the status icon asset to an icon of your liking here:

<img width="1521" alt="Screen Shot 2021-10-01 at 19 53 12" src="https://user-images.githubusercontent.com/37590873/135665651-f94389ac-1f1a-41bc-b781-a1d61dd5f2de.png">

If you are on macOS 11+, you'll also need to change the `!MACOS10_DEBUG` text in this code segment to the text `false` so your custom icon can take precedence:

<img width="896" alt="Screen Shot 2021-10-01 at 19 56 07" src="https://user-images.githubusercontent.com/37590873/135665847-9bf38859-a01a-411a-bd80-43aef81553a5.png">

You'll need to build the app afterwards of course.

**Comment by waydabber** [comment] 2021-10-01 17:59
I'll close this issue now. Thank you!

**Closed by waydabber** 2021-10-01 17:59 UTC
Labels: Status: Blocked, Type: Feature Request
