### ISSUE TITLE
turn off monitor

### ISSUE THREAD

**Issue by codelover2k** [MonitorControl/MonitorControl#823] opened 2021-12-03 17:14 UTC
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

Is it possible to turn your monitors on and off?

### Describe the solution you'd like

it would be great to have a way to turn your monitors on and off, no matter how many you are using and what monitor you want to turn on or off.

### Describe alternatives you've considered

I do not know any alternatives :(

**Comment by JoniVR** [comment] 2021-12-03 20:01
Not as of yet, however, there are various tools to do this already. 

You can either use something like https://github.com/kfix/ddcctl, or, if you want something graphically, I think [Lunar](https://lunar.fyi/) also does this.

I'm going to close this, if there's anything else, feel free to respond.

**Comment by JoniVR** [comment] 2021-12-03 20:05
Also, dupe of #721, please search for existing issues if you do check the checkbox....

**Closed by JoniVR** 2021-12-03 20:05 UTC
