### ISSUE TITLE
Can't change MB brightness in mirror mode

### ISSUE THREAD

**Issue by felixradtke** [MonitorControl/MonitorControl#437] opened 2021-05-07 12:24 UTC
**Checklist**
- [x] I have searched for existing issues
- [x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [x] I have updated MonitorControl to the latest version

**Describe the bug**
When using both the MacBook display and the external display (through USB-C), you can change the internal brightness with ctrl+F1/F2, and the monitor's brightness with F1/F2. However, when both displays are in mirror mode, you can't change the internal brightness anymore. 
**To Reproduce**
1. Activate display mirror mode in settings
2. Try to change the brightness of the MacBook display with ctrl+F1/F2
**Expected behavior**
The internal display's brightness should change.

**Environment Information (please complete the following information):**
- macOS version: 11.3.1
- Mac model: MacBook Pro 16" late 2019
- MonitorControl version: 2.1.0
- Monitor(s): LG UltraFine
- Apple Silicon/M1 (yes or no): no

**Comment by waydabber** [comment] 2021-08-17 09:10
This should be fixed in the latest betas which improves handling of mirrored displays. Please retest it and close if you find it working! Thank you!

**Comment by felixradtke** [comment] 2021-08-17 10:51
Hi @waydabber thank you for your reply. I have tested it a bit on 3.0b8. ctrl+brightness now works to control just the internal monitor, which is great! 

Controlling the external monitor isn't as reliable anymore as in previous versions. (1) It is "kind of" is changing the brightness on internal+external monitor even though the setting isn't active in MonitorControl's settings, but this just happens when display mirroring is active on macOS. (2) When mirroring is disabled, it works as expected but with much more lagging than in previous versions. 

I expect that at least (2) might be the known intel issue 'Changing the volume/brightness on Intel devices might be a bit choppy/laggy'. Thanks a lot!

**Comment by waydabber** [comment] 2021-08-17 11:50
Hi,

if you are on Intel, then the choppiness is probably due to the issue @JoniVR mentioned. Unfortunatelly I can't test that.

It is intentional that the app changes both the main and the mirrored display's brightness now (as these are basically regarded as one screen, the app can't decide which display should be controlled via keyboard based on which screen is active since both are active) - imagine a situation when one external display is mirrored to an other.

**Comment by waydabber** [comment] 2021-08-21 14:55
Hi, we have relased the [3.0.0 version](https://github.com/MonitorControl/MonitorControl/releases/tag/v3.0.0-rc1). Could you please test if this issue is resolved and report back? Thank you!

**Comment by felixradtke** [comment] 2021-08-21 21:01
Thanks, @waydabber , the RC appears much more stable on my end!
- laggy behaviour on Intel seems to be fixed

- I have the same display twice in settings (see attached). When I disable one of them, it actually works as expected: Brightness with buttons and slider just regulates the external brightness, and ctrl+brightness regulates the internal brightness, even if mirroring is active.

<img width="687" alt="Bildschirmfoto 2021-08-21 um 22 55 45" src="https://user-images.githubusercontent.com/5154969/130334559-7d906553-a3c8-4d42-8f77-10429dca14dc.png">

- There is currently just a slider for the external monitor when using the menu bar icon, I am not sure if we had multiple sliders in the past (If not: Would be nice to have)

Nevertheless, it looks like this issue is solved - thank you!

**Comment by waydabber** [comment] 2021-08-21 21:09
Hi, Farb-LCD, which is the built in display seems to be a mirror of LG HDR 4K (the wave indicates the mirrored relationship). When mirroring is enabled and both displays are Enabled for control, then both displays should be controlled at the same time. This is by design works like this and is not a bug (since the app cannot tell which one you want to control by the location of the mouse, since both has the mouse). If you want to control only one, then you have disable keyboard control for the other in a mirrored scenario. Hope this helps!

You can add the volume and contrast slider if you turn them on under the "General" ("Allgemein") tab. The internal display has no slider since it can be direclty controlled by the macOS slider.

**Comment by waydabber** [comment] 2021-08-25 10:32
I'll close this one since it should be solved. If there is any issue with this, please feel free to comment and ask for a reopen! Thank you!

**Closed by waydabber** 2021-08-25 10:32 UTC
Labels: Bug, Status: Done, Feedback/info required!
