### ISSUE TITLE
Acer XB280HK works with ddctl but not with MonitorControl

### ISSUE THREAD

**Issue by jonashaag** [MonitorControl/MonitorControl#296] opened 2020-09-29 19:31 UTC
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the Monitor Troubleshooting wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [x] I have updated MonitorControl to the latest version

**Describe the issue**
MonitorControl does not allow for changing brightness, but `ddctl` does.

**Expected behavior**
Brightness control should be available (disabled/greyed out).

**Additional context**
`ddctl` changes the brightness correctly, but reports errors.

```
$ ./ddcctl -d 1 -b 255
D: NSScreen #478281277 (1920x1080 0°) HiDPI
I: found 1 external display
I: polling display 1's EDID
I: got edid.serial: #ASMkbeNoxMPd
I: got edid.name: Acer XB280HK
D: action: b: 255
D: setting VCP control #16 => 255
E: Failed to send DDC command!
```

Possible values seem to be in [0, 100].

**Environment Information (please complete the following information):**
 - macOS version: 10.15.6
 - MonitorControl version: 2.1.0
 - Monitor(s): Acer XB280HK
 - Mac model: MacBook Pro 2015
 - Monitor Cable(s)/Connection(s): (e.g. DisplayPort) DisplayPort -> DisplayPort

**Comment by JoniVR** [comment] 2020-09-30 17:05
So if I understand correctly, ddcctl reports the sending of the command failed but it works anyways? I could perhaps try to provide a build where the check for ddc is disabled for you to test (or you could test it yourself if you know how).

Do keep in mind that we're not using ddcctl under the hood anymore but perhaps if we disable the ddc check it might work. If that's the case we could provide it as an "advanced prefs" setting.

**Comment by jonashaag** [comment] 2020-09-30 22:12
I guess that would work!

**Comment by jonashaag** [comment] 2020-09-30 22:13
And yes, the command seems to be executed correctly, even though an error is reported.

**Comment by waydabber** [comment] 2021-08-21 17:14
Hi, you might want to try version 3.0.0 to confirm that the issue is still present (or not). If it does not work please provide a screenshot of the Displays tab so we might see how MonitorControl recognizes the display (controllable or not). Thank you!

**Comment by jonashaag** [comment] 2021-08-21 17:51
Unfortunately I don’t have that particular display anymore so won’t be able to test :(

**Comment by waydabber** [comment] 2021-08-21 17:54
Ok, no problem. Thanks for the reply! Hope the new display works properly with MonitorControl. :)

I'll close this issue then.

**Closed by waydabber** 2021-08-21 17:54 UTC
Labels: Monitor Issue, Feedback/info required!
