### ISSUE TITLE
Enable clamshell mode from MonitorControl

### ISSUE THREAD

**Issue by JaKXz** [MonitorControl/MonitorControl#404] opened 2021-03-12 17:18 UTC
**Checklist**

- [x] I have searched for existing issues

**Describe the solution you'd like**
I think it would be amazing if it was possible to trigger macOS' "clamshell" mode so you only use your external display while your laptop is still open. I'm not sure if it's possible but I figured this app might be an interesting place where it could be implemented. It would be nice to have the benefits of clamshell mode while still having access to say the trackpad or webcam, or even just leaving the laptop open for better air flow during processor intensive tasks. Again, not sure if this is even possible but wanted to see if this might be possible. Sorry if this has been asked about before, I couldn't find anything in my quick search.

**Describe alternatives you've considered**
ATM I just use "clamshell" mode as you'd expect, with a usb hub and monitor plugged in to my closed laptop; status quo and totally fine.

**Comment by waydabber** [comment] 2021-08-21 12:25
Hi @JaKXz - I am not sure if this is easily possible by design. The best you can do is to set your internal display to mirror your external display and turn the internal display brightness to zero. This will basically result in what you want to achieve.

Hope this helps!

I'll close this issue but if there is anything else I can help you with, let me know!

**Closed by waydabber** 2021-08-21 12:25 UTC
Labels: Information, Feature Request
