### ISSUE TITLE
Hotkeys doesn't work on fullscreen app on second display

### ISSUE THREAD

**Issue by nekrasovdmitriy** [MonitorControl/MonitorControl#30] opened 2018-04-14 11:56 UTC
If any app is open in fullscreen on second monitor, hot keys of MonitorControl on that monitor doesn't work, you have to switch back to desktop view on second display to have them work again.
On main display hot keys work anywhere, on fullscreen apps also.

**Comment by the0neyouseek** [comment] 2018-04-14 17:12
Hi @nekrasovdmitriy,

That's weird, the hot keys should work independently of the monitor used and not be affected by fullscreen apps at all.

What could be the problem here is that the app determine what screen to apply the hot key to directly from the system using [NSScreen main](https://developer.apple.com/documentation/appkit/nsscreen/1388371-main). This function choose the _'current'_ screen depending on keyboard, mouse focus and usage. 
So, for example, if you've just launched an app in fullscreen and moved your mouse with no further interaction with the app nor the second screen yet, the hot key would be applied to the previous screen.
There's nothing I can really do about this behaviour as it's native.

Is this what's happening to you ?

**Comment by ifixr** [comment] 2018-06-18 20:43
I can confirm this. I'm reading this thread in Safari in full screen and hitting the brightness keys control my built-in screen.

**Comment by the0neyouseek** [comment] 2018-06-21 07:05
Hi @ifixr & @nekrasovdmitriy,

As i'm currently working full time, I don't have much free time to develop MonitorControl but I'll try to look this up asap and fix it in the next version.

Have a nice day.

**Comment by odenak** [comment] 2019-08-14 15:13
I also have this problem, but I found that sometimes after my MBP wakes from sleep, it does work on the fullscreen apps on the external monitor.

**Comment by kikiwora** [comment] 2019-10-24 09:05
The same issue here.

But for me, the second monitor is actually the primary monitor of two of them due to issues with brightness control via HDMI on Mac Mini 2018.

As for me, this is at least **medium** priority, since it greatly impacts user flow

**+1** for higher priority

**Comment by sn0wyfall** [comment] 2020-06-06 23:14
Thank you for the reference

**Comment by sn0wyfall** [comment] 2020-10-07 17:47
@JoniVR Hey, was this issue ever fixed? I just downloaded version 2.1.0 but it seems like brightness controls still don't work in full screen apps. Maybe there was a regression?

**Comment by JoniVR** [comment] 2020-10-07 17:48
Hmm it should be, I'll take a another look when I get time.

**Comment by nekrasovdmitriy** [comment] 2020-10-07 18:16
I can confirm that problem still persists

**Comment by sn0wyfall** [comment] 2020-10-19 18:15
@JoniVR Thanks a lot! I think I've updated to every version since the issue was opened, but the issue was never fixed on any of the versions as far as I can tell. Looking forward to it, since this is one of my most used apps :D

**Comment by shahanesanket** [comment] 2020-11-02 15:25
Hi @JoniVR , this problem still exists. Hack to get it working is to leave the monitor control window open on the desktop of the second screen, then the hotkeys then work on full screen apps as well. It would be very useful to have it working without this hack. Thanks!

**Comment by nekrasovdmitriy** [comment] 2020-11-02 19:58
> Hi @JoniVR , this problem still exists. Hack to get it working is to leave the monitor control window open on the desktop of the second screen, then the hotkeys then work on full screen apps as well. It would be very useful to have it working without this hack. Thanks!

Hack works

**Comment by sn0wyfall** [comment] 2020-12-19 23:15
I just found out about [Lunar](https://github.com/alin23/Lunar). It seems to work fine in fullscreen apps and also has some more advanced features I'm interested in. I'll miss MonitorControl! It's a great app.

**Comment by waydabber** [comment] 2021-08-20 18:37
Hi, this should be fixed in an upcoming 3.0.0 version (beta8 still do not have this). The location of the mouse cursor will determine the controlled display including if the given screen has a full screen app (previous implementation failed on this).

https://github.com/MonitorControl/MonitorControl/issues/424

**Comment by waydabber** [comment] 2021-08-20 18:39
If you have any issue with this in the upcoming 3.0.0 version, please let me know here.

https://github.com/MonitorControl/MonitorControl/issues/424

I'll close this issue since more technical details are available over there.

Thank you!

**Closed by waydabber** 2021-08-20 18:39 UTC
Labels: Bug, Priority: Minor, Status: Done
