### ISSUE TITLE
Not working after sleep mode

### ISSUE THREAD

**Issue by dnnsppp** [MonitorControl/MonitorControl#530] opened 2021-08-22 12:22 UTC
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

Hi there,

it’s perfect and works totally fine with the new Huawei MateView.
The only issue I have once in a while: Sometimes after my MacBook was in sleep the app is not working / responding. 
Both, the function keys for brightness and sliders do not work anymore. After closing and opening the app again, everything works fine. 

Anyone knows why this issue can occur?

Cheers
Dennis

### Steps to reproduce

Occurs randomly

### Expected behavior

This bug occurs randomly. Most of the time it works like magic. 

### Environment Information (please complete the following information)

```markdown
- macOS version: 11.5.2
- Mac model: M1, MacBook Pro
- MonitorControl version: 3.0.0 RC1
- Monitor(s): Huawei MateView, 28
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment] 2021-08-22 13:25
Hi, after sleep there is an approx. 5 seconds waiting period until all devices are safely resumed. During this time all DDC communications are blocked. After this period the system reloads the display configuration and then enables operation. During this time the brightness and volume OSD will have a lock when you try to use the keyboard.

Are you sure that you are not trying to use the app within this approx. 5 seconds of safety time?

**Comment by dnnsppp** [comment] 2021-08-22 13:41
I understand that but it does not work even after 10 seconds or 1 minute. I have to restart it.

**Comment by waydabber** [comment] 2021-08-22 14:49
Well, this is obviously not good then. :)

Could you try the following (whithout restarting the app):

- If you open/close the lid - does it solve the problem?
- If you connect/disconnect the display - does it solve the problem?

Also please can you send me the screenshot of the Displays tab when it works, and after sleep when it doesn't work?

After sleep if you try to use the brightness keys what happens? Do you see the macOS brightness OSD changing or do you see a lock symbol?

Thank you!

**Comment by waydabber** [comment] 2021-08-22 15:00
Also, you might want to try to change the DDC read polling mode to 'None' - as the issue might be related that after sleep, the app receives erroneus information from the display about supported control ranges and that's why controls look disabled. Setting this option to 'None' will disable this functionality and allow a default control range.

<img width="803" alt="Screen Shot 2021-08-22 at 17 00 09" src="https://user-images.githubusercontent.com/37590873/130359881-50837972-0fe6-4788-bfd0-79a09c557a30.png">

**Comment by dnnsppp** [comment] 2021-08-22 16:20
Thanks for your feedback. I will try it out and get back to you when I have more information on it.
What display tab are you referring to?

Cheers,
Dennis

**Comment by waydabber** [comment] 2021-08-22 16:50
Hi, I was thinking about the one that is visible on my screenshot above.

- An other thing that you  might try is that you turn off 'Use hardware DDC control' and see if the display is controlled that way (this might let us know if the problem lies with DDC or with display detection in general).

Sorry for the overwhelming amount of things to try. :)

**Comment by dnnsppp** [comment] 2021-08-22 16:54
I will try it out :) 

Display tab: I have the same settings as you.

Haha, no problem!

**Comment by waydabber** [comment] 2021-08-22 17:17
Ok. But please look at the Displays tab when the application is in the state when it can't control the display. Also, in this mode you can try disabling Hardware control and also try opening/closing the lid to force a reconfiguration.

**Comment by dimitrij2k** [comment] 2021-08-23 05:22
Same Problem here with LG 32UN880 Display and MacBook Air (M1).

Sometimes it work after sleep, sometimes I have to restart the app. Maybe its possible to "restart the service" of the app after sleep?! But I will try the DDC read polling later...

**Comment by waydabber** [comment] 2021-08-23 06:30
Hi, there is no service to talk of actually.

I'd need to know these details to understand things better:

- If you open/close the lid - does it solve the problem?
- If you connect/disconnect the display - does it solve the problem?
- What is happening when you try to use the brightness keys? Does the OSD appear and how does it behave, does it have a Lock symbol or not?
- If 'Use hardware DDC control' is off, then is the brightness changing via software (this might let us know if the problem lies with DDC or with display detection in general).
- Does the issue happen with polling set to 'None'?
- How does the Displays tab look before sleep and after sleep when the issue is happening?

Thank you very much for your help!

**Comment by waydabber** [comment] 2021-08-24 07:32
Hi @dimitrij2k thank you! There is a five seconds delay after sleep to let everything settle and the display wake up properly (displays with slower firmares or CCFL backlights take a lot of time waking up).

Probably there should be some advanced settings to have the ability to fine tune things:

- Wake-up wait period after sleep
- Wait period after display reconfiguration
- Show 'Redetect displays' option in the menu.

**Comment by dimitrij2k** [comment] 2021-08-24 20:35
@waydabber thank you, for your help. Even after a longer Period of waiting, the Control don't work. I created a Video, to show the misbehavior.

What I found out:
- Boot MacBook Air (M1) and start Software - works
- Connect/Reconnect USB-C Cable - works
- Sleep/Wake-up (less then a some minutes) - works
- Sleep/Wake-up after a longer Periode - **don't work!**

The last Scenario is shown in the Video: [https://youtu.be/gSTKxvRyGno](url)

**Comment by waydabber** [comment] 2021-08-24 21:00
Thank you! I think after a longer sleep the 5 seconds of expected recovery period might not be enough for some setups. Thank you for your diligence regarding the other questions, hopefully those answers will help to further narrow down the problem.

**Comment by dimitrij2k** [comment] 2021-08-28 12:12
Unfortunately I have a lot to do in my job, so I can't complete the "bug hunting". But open the lid and close it again seems (in the couple few days) to eliminate the problem. So it don't need to restart the app, to fix the problem. Very interesting! But I will answer all of your questions. hopefully this weekend!

**Comment by krissp** [comment] 2021-08-29 02:46
Thanks, @waydabber for looking into this

I also seem to be running into the described behavior/issue.
- M1 MacBook Pro
- MacOS 11.5.1
- DELL U2520D with USB-C connection

So far, can confirm restarting the app, or opening/closing the lid re-enables brightness control after it's stuck following a long sleep.

Will also try to help you answer more of the debug questions from my setup... just waiting for it to get stuck again :)

**Comment by waydabber** [comment] 2021-08-29 08:40
Thank you for the info!

- If you open/close the lid when the app is in an unresponsive state - does it solve the problem? - **Yes**
- If you connect/disconnect the display - does it solve the problem? - **Probably Yes**
- What is happening when you try to use the brightness keys? Does the OSD appear and how does it behave, does it have a Lock symbol or not? - **Unknown**
- If 'Use hardware DDC control' is off, then is the brightness changing via software (this might let us know if the problem lies with DDC or with display detection in general). - **Unknown**
- Does the issue happen with polling set to 'None'? - **Unknown**
- How does the Displays tab look before sleep and after sleep when the issue is happening? - **Unknown**

It would be great if I could get the answers for the unknowns. The issue might be that after a long sleep simply a longer wait period is needed until the app reconfigures the display but other factors might be involved as well.

Btw. how long it takes from initiating wake to the desktop to appear normally with your setup after a long sleep?

**Comment by krissp** [comment] 2021-08-29 19:16
- If you open/close the lid when the app is in an unresponsive state - does it solve the problem? - **Yes**
- If you connect/disconnect the display - does it solve the problem? - **Confirmed, yes**
- What is happening when you try to use the brightness keys? Does the OSD appear and how does it behave, does it have a Lock symbol or not? - **For the external display, OSD does not appear – as if the brightness key press is completely unrecognized; when I have the build-in display open, OSD appears and control continues working as expected for the built-in**
- If 'Use hardware DDC control' is off, then is the brightness changing via software (this might let us know if the problem lies with DDC or with display detection in general). - **Interesting... brightness is not changing via software, and it actually seems like "Control method: Software" isn't working in any condition for this display. It seems I need "Use hardware DCC control" checked for the control to work. Not sure if this helps out, but curiously, when operating under Control method: Software, the behavior seems identical to the original issue described here (can't control brightness, and OSD does not appear when brightness keys are pressed)**
- Does the issue happen with polling set to 'None'? - **I'm giving this a try now, and will report back**
- How does the Displays tab look before sleep and after sleep when the issue is happening? - it looks the same before and after, see attached screenshot ![Screen Shot 2021-08-29 at 2 48 03 PM](https://user-images.githubusercontent.com/2407587/131262040-578383b8-9d36-44cd-9161-ba823b0c2654.png)

> Btw. how long it takes from initiating wake to the desktop to appear normally with your setup after a long sleep?
I'm going to need to pay closer attention and follow up on this as well. It doesn't feel noticeably long though, a couple of seconds.

**Comment by waydabber** [comment] 2021-08-29 20:11
'Interesting... brightness is not changing via software, and it actually seems like "Control method: Software" isn't working in any condition for this external display.'

For this to work you also need to have 'Enable software dimming if required' enabled in General. This is now enabled by default but if you had an earlier beta it might be disabled due to settings saved. Can you check if this option is enabled? Thank you!

**Comment by krissp** [comment] 2021-08-29 20:17
You're right. I had an earlier beta and 'Enable software dimming [...]' was off. After taking care of that, brightness is now changing. Seems like this is a viable workaround for the time being.

**Comment by waydabber** [comment] 2021-08-29 20:23
I didn't mean this to be a workaround, just mentioned the fact that probably this is the problem with that. 

Opening/closing the lid or reconnecting the display both forces MC to redetect displays. The fact that this solves the problem probably means that for some reason MC does not properly detects the service port for the display after a long sleep as it might not be available yet (or maybe for some reason the service port changes). I'll have to look into this issue and try to replicate it.

**Comment by krissp** [comment] 2021-08-29 20:27
Yep, I walked that back shortly :) -- edited my previous comment after realizing that software dimming is literally just darkening colors.

**Comment by krissp** [comment] 2021-08-29 20:31
You mentioned "maybe for some reason the service port changes", any way I can help you check this?

**Comment by dimitrij2k** [comment] 2021-08-29 20:52
I tried to make more tests today, but i cant get my Macbook run into the bug. I wanted to reproduce it, but it worked every time! Since i opened once the macbook while the bug comes up, it works now every time. I reboot a couple times my machine, but not run into the bug.  Strange… but i will male more tests the next days…

**Comment by waydabber** [comment] 2021-08-30 17:22
Hi all, I experienced this problem myself as well today so at least I know what we are talking about. Problem is I can't seem to induce it again, especially in a controlled environment (so I can debug the code), but I'll try. :)

**Comment by waydabber** [comment] 2021-08-31 09:48
Ok, I was able to reproduce the issue reliably and was able to debug it. The issue is that there are some instances when the display configuration changes with regards to the service port that the app uses to communicate with the display on Apple Silicon but macOS does not send a reconfiguration event so the app is trying to communicate using an outdated service port. This seems to happens whenever during sleep the display looses power or enters a deep sleep so the link between the mac and the display is severed, but the display cable remains attached during sleep.

I'll change the sobering logic (this happens after sleep) so the app always does a display reconfiguration no matter what.

**Comment by waydabber** [comment] 2021-08-31 12:30
Here is an [unsigned test build](https://www.dropbox.com/s/w1md5rjyll0lsyo/MonitorControl.zip?dl=1) that should fix this issue if somebody would like to try it out. This requires you to click 'Open Anyway' in Preferences/Security. The source of this build [is here](https://github.com/MonitorControl/MonitorControl/tree/temp/debug) - if you don't trust in unsigned builds and want to build it yourself. Thank you!

**Closed** 2021-09-01 18:39 UTC
Labels: Bug, Status: Done, Architecture: arm64
