### ISSUE TITLE
Stops working after waking from sleep (M1 + 3.0.0 Beta 5)

### ISSUE THREAD

**Issue by callahad** [MonitorControl/MonitorControl#507] opened 2021-08-09 15:03 UTC
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [x] I have updated MonitorControl to the latest version

**Describe the bug**

MonitorControl fails to adjust brightness after the computer wakes from sleep.

**To Reproduce**

1. Allow computer to enter sleep.
2. Wake with mouse or keyboard.
3. Attempt to use the MonitorControl menu to adjust brightness.

Nothing happens. Power cycling or disconnecting/reconnecting the monitor restores MonitorControl functionality.

**Environment Information (please complete the following information):**

- macOS version: 11.4
- Mac model: 13-inch, M1, 2020 — MacBookPro17,1
- MonitorControl version: 3.0.0 Beta 5 (build 1513)
- Monitor(s): Dell U2917W monitor via DisplayPort, passing through a Toshiba Thunderbolt 3 Dock:
- Apple Silicon/M1 (yes or no): Yes

**Comment by callahad** [comment] 2021-08-09 15:06
It seems like things still work if woken quickly after entering sleep (or maybe it's random / there's a race condition somewhere?) so I can't reproduce the issue quickly, but I have had it occur twice today.

I don't recall this being a problem in prior betas.

**Comment by fbirlik** [comment] 2021-08-09 16:27
Macbook Pro, M1
Philips 328E over usb-c hub

**Beta-5** fails to control brightness over slider or keyboard keys after wake up.  To reproduce, press sleep button on keyboard (apple menu > sleep should be ok), wait ~5 minutes, wake computer up.  Can't control brightness afterwards.

**Beta-4** is also affected

**Beta-3** is also affected

**Comment by fbirlik** [comment] 2021-08-10 15:10
> Macbook Pro, M1
> Philips 328E over usb-c hub
> 
> **Beta-5** fails to control brightness over slider or keyboard keys after wake up. To reproduce, press sleep button on keyboard (apple menu > sleep should be ok), wait ~5 minutes, wake computer up. Can't control brightness afterwards.
> 
> **Beta-4** is also affected
> 
> **Beta-3** is also affected

experimental/apple-silicon
v3.0.0-beta5-19-g5333f2c
b1687

fixes the sleep/wakeup issue for me.

**Comment by waydabber** [comment] 2021-08-11 16:08
Yes, this issue will be fixed in the upcoming beta.

**Comment by JoniVR** [comment] 2021-08-11 18:30
Can you try on beta 6 and let us know if it helps?

**Comment by fbirlik** [comment] 2021-08-11 21:30
> Macbook Pro, M1
> Philips 328E over usb-c hub
> 
> **Beta-5** fails to control brightness over slider or keyboard keys after wake up. To reproduce, press sleep button on keyboard (apple menu > sleep should be ok), wait ~5 minutes, wake computer up. Can't control brightness afterwards.

**Beta-6** fixes the issue for my setup

**Comment by JoniVR** [comment] 2021-08-12 19:11
Going to close since it looks fixed, if you continue to have issues, feel free to comment in #515 (we like keeping beta feedback seperate)

**Closed by JoniVR** 2021-08-12 19:11 UTC
Labels: Architecture: arm64, Beta

**Comment by callahad** [comment] 2021-08-12 21:37
I've not been able to repro in Beta 6; verifying that this appears fixed.
