### ISSUE TITLE
Works on one Mac (MBP) but not the other (Mac Mini) - Using the same cable to the same display

### ISSUE THREAD

**Issue by damoen** [MonitorControl/MonitorControl#265] opened 2020-07-20 16:17 UTC
I have this strange problem where MonitorControl Works on one Mac but not the other - using the same cable to the same display. This is similar to #248  except I am not connecting two Macs to the same monitor, at the same time. We both seem to have the same problem with our latest Mac Mini's.

**Mac A:**
Retina MBP 15" Mid 2012 (Macbook Pro10,1)

**Mac B:**
Mac Mini 2018 (Macmini8,1)

**Monitor:**
LG 43UN700-B

**MonitorControl version:**
Both running v1.7.1

**macOS version:**
Both running 10.15.6

**Problem:**
MC works on Mac A but it does not work on Mac B, using the very same cable and HDMI input.

**What I have tried**
- Various HDMI cables, even though it is irrelevant, as the same cable that works on Mac A does not work on Mac B.
- Reinstalled macOS on Mac B
- Tried updating to v2.0.0
- Tried the brew release

**What I have not tried**
~~ddcctl on Mac B~~

**Observations:**
I can controll volume/brightness on Mac B **over HDMI** IF and only when a second output (USB-C) is connected - in addition to the HDMI. I am certainly on the HDMI source when controlling volume/brightness, not USB-C (although this works as well) under this condition. However I have not tried multiple HDMI connections to the same display, as the Mac Mini only has a single HDMI output.

**Why not just use USB-C instead of HDMI**
Because I need it for another box (running Windows)

The only thing I can think of is that MonitorControl somehow does not work as expected on HDMI 2.0, as this is virtually the only difference between my machines. I am not sure but I think my older MBP supports HDMI 1.4 at best. Let me know if there is any way I can help debug this.

Lastly, thank you for this awesome app. I really cannot live without it, so big thanks to everyone who've worked on this.

**Comment by damoen** [comment] 2020-07-20 18:31
Just tried ddcctl. It detects the display but controls doesn't seem to work.

```
dan@Daniels-Mac-mini ddcctl % ./ddcctl           
D: NSScreen #459113722 (3840x2160 0°) 163.00 DPI
I: found 1 external display
2020-07-20 20:29:03.026 ddcctl[57104:1409688] Usage:
ddcctl 	-d <1-..>  [display#]
	-w 100000  [delay usecs between settings]

----- Basic settings -----
	-b <1-..>  [brightness]
	-c <1-..>  [contrast]
	-rbc       [reset brightness and contrast]

----- Settings that don't always work -----
	-m <1|2>   [mute speaker OFF/ON]
	-v <1-254> [speaker volume]
	-i <1-18>  [select input source]
	-p <1|2-5> [power on | standby/off]
	-o         [read-only orientation]

----- Settings (testing) -----
	-rg <1-..>  [red gain]
	-gg <1-..>  [green gain]
	-bg <1-..>  [blue gain]
	-rrgb       [reset color]

----- Setting grammar -----
	-X ?       (query value of setting X)
	-X NN      (put setting X to NN)
	-X <NN>-   (decrease setting X by NN)
	-X <NN>+   (increase setting X by NN)

dan@Daniels-Mac-mini ddcctl % ./ddcctl -d 1 -b \?
D: NSScreen #459113722 (3840x2160 0°) 163.00 DPI
I: found 1 external display
I: polling display 1's EDID
I: got edid.name: LG HDR 4K
D: action: b: ?
D: querying VCP control: #16 =?
E: No data after 10 tries! 
E: DDC send command failed!
E: VCP control #16 (0x10) = current: 0, max: 0

dan@Daniels-Mac-mini ddcctl % ./ddcctl -d 1 -b 20
D: NSScreen #459113722 (3840x2160 0°) 163.00 DPI
I: found 1 external display
I: polling display 1's EDID
I: got edid.name: LG HDR 4K
D: action: b: 20
D: setting VCP control #16 => 20
```

**Comment by damoen** [comment] 2020-07-20 18:37
Looks like there is a problem with ddcctl and Mac Mini (2018)

https://github.com/kfix/ddcctl/issues/46

**Comment by zimmermanpro** [comment] 2020-07-22 12:06
I agree, just bought the 2020 mac mini (2018) and although it recognises the display and shows volume going up and down it has no effect. I am using HDMI

**Comment by damoen** [comment] 2020-07-22 14:40
Ended up purchasing a simple USB-C > 4K HDMI adapter from Satechi which solved my problem. My HDMI port is still useless though.

**Comment by Jeremaster101** [comment] 2020-08-04 22:42
I'm experiencing the same issue, as well as another issue linked to this one. Not only does changing the brightness and volume not actually do anything, it will also sometimes cause the display output to stop working, meaning I have to restart my Mac Mini to get my display working again. This is using the same display and HDMI cable that I used for a MBP, which worked fine with MonitorControl.

**Comment by dieoma76** [comment] 2020-10-10 10:09
Interesting finding on this, somehow related to #267 and this issue here: When i configure Split screen (using obviously same cables etc) in my LG5k the display is differently recognized in Monitorcontrol.

LG5K in **Fullscreen** - Vendor (Monitorcontrol **NOT** working): **0x9E6D**
![LG_FULL_Thunderbolt](https://user-images.githubusercontent.com/65195997/95652410-0f003500-0af1-11eb-973b-7d2620804938.png)

LG5K in **Splitscreen** - Vendor (Monitorcontrol **DOES** work): **0x1E6D**
![MacMini_smallDP](https://user-images.githubusercontent.com/65195997/95652344-87b2c180-0af0-11eb-9083-4a734ba7e221.png)
Model and ID stays the same - does this help troubleshooting or to find a workaround?

**Comment by Massi-X** [comment] 2020-12-30 16:45
The same here, i add my experience here:

- Mac Mini 2010 with Samsung C24F390 display connected via HDMI, all works well with MonitorControl and also similar applications (External Brightness,Native Display Brightness)
- Mac Mini 2014 connected to the same display via HDMI, it does work sometimes after you repeatedly press up/down key and then stops working. And then works again. But always glitchy. So this is definitively a problem with my Mac (and others?), previously I also had another Samsung monitor with the same problem, and with the 2010 model it was working well.

Last thing to notice that the 2014 from day one sometimes showed strange artifacts when starting up (in place of Apple logo) like random dots or garbage screen, after boot it works well also with intense graphic usage. Don't know if it has something to do with it

If this can be helpful...

**Comment by Massi-X** [comment] 2021-01-05 17:41
Seems interesting, I will try next Thursday to look into it

**Comment by Massi-X** [comment] 2021-01-08 09:18
@damoen Hi, the display doesn't have an indication of the current signal type (I suppose is RGB anyway) but I didn't bother too much and followed [this](https://gist.github.com/ejdyksen/8302862) procedure because the one you linked doesn't work with Big Sur. Well, the colors went completely off (and System Profiler show "forced RGB mode"), apart from that the controls where unusable as before. ddctl doesn't work either. Seems like HDMI port has some problems, Maybe I'll try to buy an USB to HDMI adapter. If I do, I report back the results
Tell me if you need more informations or tests

**Comment by root4loot** [comment] 2021-01-09 19:13
@Massi-X Did some experimenting and I can now confirm that the input color format has nothing to do with it. I have three monitors connected now and for some reason, macOS displayed YPbPr on the faulty HDMI display. This displays is now forced to RGB after running the patch-edid.rb script to no avail.

At the same time I can confidently say that the problem is not hardware related as ddctl/MC works over HDMI on the Mac Mini 2018 under certain conditions when multiple displays are connected - similar to what was observed by @dieoma76. Under this circumstance, the problem then shifts from HDMI to the other display that is connected via USB-C. Having said that I believe there is something off with the display manager in macOS in relation to the HDMI out that is sitting on the Mac Mini 2018.

**Comment by damoen** [comment] 2021-01-09 19:18
@Massi-X Did some experimenting and I can now confirm that the input color format has nothing to do with it. I have three monitors connected now and for some reason, macOS displayed YPbPr on the faulty HDMI display. This monitor is now forced to RGB after running the patch-edid.rb script, but to no avail. At least all of my monitors are displaying correctly in RGB now but the problem persists.

On the other hand I can confidently say that the culprit is not related to hardware as ddctl/MC works over HDMI on the Mac Mini 2018 under certain conditions when multiple displays are connected - similar to what was observed by @dieoma76. In that circumstance, the problem then instead shifts from HDMI to some other display that is connected via USB-C. Having said that I believe there is something off with the display manager in macOS in relation to HDMI on the Mac Mini 2018 specifically.

**Comment by Massi-X** [comment] 2021-01-09 21:59
Maybe it has something to do with alt mode (see #102)?
I can't understand why, at least in my case, sometimes works by continuously pressing the fn key! Seems like a strange problem
On a related note I noticed my mac doesn't have an usb c port... I will buy a thunderbolt to hdmi adaptor to test if it works

**Comment by damoen** [comment] 2021-01-10 02:37
@Massi-X AFAIK alt mode is mostly a concern for adapters nowadays that convert video signals from HDMI to USB-C / DisplayPort or vice versa.

Note that Thunderbolt 3 is USB type C (USB-C) so you don't need an expensive Thunderbolt adapter just to convert the signal. Most adapters will do but stay away from the cheap ones as they often lack the alt mode technology. I ended up getting [this](https://satechi.net/products/aluminum-type-c-to-hdmi-adapter-4k-60hz?variant=35099869065) which is high quality, reasonably priced and works perfectly well.

**Comment by Massi-X** [comment] 2021-01-10 11:17
Yeah but my mac has only thunderbolt 2. The adapter is worth 10 eur so it's not expensive at all.
I think is almost 4 years that I deal with this problem, maybe it is worth a try!

**Comment by Massi-X** [comment] 2021-01-11 09:07
Wow Amazon is pretty fast! I received the adapter and can confirm that, at least in my case, this was the problem. Now it works flawlessly!
Nevertheless it can be interesting finding out why MonitorControl doesn't work on the standard output

**Comment by waydabber** [comment] 2021-08-19 07:55
Hi, since the 2018 Mini HDMI problem (as well as the 2020 M1 Mini HDMI problem) is a hardware issue and there is nothing to fix in MonitorControl regarding this, I'll close this issue.

**Closed by waydabber** 2021-08-19 07:55 UTC
Labels: Monitor Issue

**Comment by Massi-X** [comment] 2021-08-19 10:23
Hi @waydabber not interested in this anymore as I have fixed it with the adapter, but worth pointing out that in my case it was a 2014 Mac mini with full size port. Bye!

**Comment by waydabber** [comment] 2021-08-19 12:49
Humm. Didn't know hat model had this issue as well. :s Thanks for the reply!
