### ISSUE TITLE
Have contrast adjusted at same time as brightness?

### ISSUE THREAD

**Issue by OliverPearmain** [MonitorControl/MonitorControl#849] opened 2021-12-18 17:36 UTC
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Question

I personally find that adjusting contrast in conjunction with brightness gives me the optimum monitor experience as the lighting changes through-out the day. 

I currently achieve this by manually adjusting the contrast via the menu/slider after tweaking the brightness with the dedicated brightness keys. 

It would be fantastic if I were able to setup Monitor Control to do adjust the contrast automatically as I increase/decrease the brightness with the keyboard. 

For consideration: I think in an ideal world one would be able to set the range of contrast and brightness, i.e. a start and end values for both contrast and brightness, and Monitor Control would move through each range accordingly.

**Comment by JoniVR** [comment] 2021-12-18 17:42
Duplicate of #620. Toggle advanced at the bottom of displays tab and follow along with the last comment.

**Closed by JoniVR** 2021-12-18 17:42 UTC
