### ISSUE TITLE
Volume Up/Down Graphic Toggle

### ISSUE THREAD

**Issue by matthewonghai13** [MonitorControl/MonitorControl#389] opened 2021-02-12 19:42 UTC
**Checklist**

- [x] I have searched for existing issues

**Is your feature request related to a problem? Please describe.**

I have an LG 32UL950 monitor that works great with MonitorControl, but the volume graphic included with MonitorControl overlaps the native monitor volume control that pops up when volume is changed with the volume keys.

**Describe the solution you'd like**

It would be great to have a simple toggle in the preferences to disable the volume up/down graphics in MonitorControl.

**Describe alternatives you've considered**
I tried to find ways to disable the native volume graphic, but there isn't a way to disable it (and I'm sure many other monitors are similar).

**Comment by waydabber** [comment] 2021-08-19 07:22
This function will be added in 3.0.0. :)

Since this is a duplicate of this https://github.com/MonitorControl/MonitorControl/issues/480 (although your request is the older one, sorry) - I'll close this issue, but you can keep track and add a reply there. Thanks!

**Closed by waydabber** 2021-08-19 07:22 UTC
Labels: Feature Request
