### ISSUE TITLE
Screen flashes when switching spaces with keyboard shortcut

### ISSUE THREAD

**Issue by sebastianknell** [MonitorControl/MonitorControl#1015] opened 2022-04-26 02:44 UTC
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

When switching to another space using a keyboard shortcut (^1, ^2, or a custom one) the screen flashes to the max brightness before going back to the brightness I had. Note that this does not seem to happen (or maybe is not noticeable) when switching to the next/prev space (with ^ + arrow-left, or ^ + arrow-right).

### Steps to reproduce

Switch spaces using the default mission control keyboard shortcut (^ + space number).

### Expected behavior

The app keeps the same brightness without flashing when one switches spaces using a keyboard shortcut.

### Anything else?

I'm running at 75 Hz. Don't know if that could have something to do.

### Environment Information (please complete the following information)

```markdown
- macOS version: 12.2 Monterrey
- Mac model: MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports)
- MonitorControl version: v4.0.2
- Monitor(s): LG 27MK600M-B
- Apple Silicon/M1 (yes or no): no
```

**Comment by waydabber** [comment] 2022-05-01 09:14
HI @sebastianknell - This typically happens when overlay (shade) is used instead of gamma dimming. This is normal, overlays do not show during switching spaces.

If this is not the case, please let me know!

**Comment by sebastianknell** [comment] 2022-05-01 17:26
Ok I disabled the avoid gamma table manipulation setting in the displays section and the issue seems to be gone. Is that what you meant?

**Comment by the0neyouseek** [comment] 2022-05-01 21:31
Yes, the *avoid gamma table manipulation* should mostly be used if you have an incompatibility caused by a third party app such as [f.lux](https://justgetflux.com/). I'll close this issue as it seems everything is fixed for you.

**Closed by the0neyouseek** 2022-05-01 21:31 UTC
Labels: Status: Feedback needed from issue reporter
