### ISSUE TITLE
Samsung C34J79x + M1 MacBook Pro

### ISSUE THREAD

**Issue by JAVAL0RD** [MonitorControl/MonitorControl#342] opened 2020-12-05 16:36 UTC
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the Monitor Troubleshooting wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [x] I have updated MonitorControl to the latest version

**Describe the issue**
A clear and concise description of the problem.
Latest version of app initializes, and brightness box pops up when buttons are pressed, but nothing changes. Audio is completely non responsive.

**Expected behavior**
It's worked on this monitor in the past, but I suspect its changing computers to the new M1 chip MacBook Pro.

**Screenshots**

**Additional context**

**Environment Information (please complete the following information):**
 - macOS version: Big Sur 11.0
 - MonitorControl version: 2.1.0
 - Monitor(s): Samsung C34J79x
 - Mac model: 2020 M1 MacBook Pro
 - Monitor Cable(s)/Connection(s): (e.g. DisplayPort) Thunderbolt 3

**Comment by JoniVR** [comment] 2020-12-05 16:36
Duplicate of #323

**Closed by JoniVR** 2020-12-05 16:36 UTC
Labels: Type: Monitor Issue
