### ISSUE TITLE
One monitor doesn't update when when using 2 external monitors

### ISSUE THREAD

**Issue by MarkEstefanos** [MonitorControl/MonitorControl#243] opened 2020-06-19 01:22 UTC
**Checklist**
- [x] I have searched for existing issues
- [x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [x] I have updated MonitorControl to the latest version

**Describe the bug**
When using 2 identical external monitors, the sliders for both monitors only effect the first monitor, with neither slider ever effecting for the second monitor. 

If I check "Change Brightness/Volume for all screens" the second monitor doesn't change at all when I change the brightness

When using only 1 monitor at a time everything works as expected with either monitor. 

**To Reproduce**
1. Plug in both monitors.
2. Run MonitorControl.
3. Attempt to change the brightness on either.

**Expected behavior**
Each slider would effect its respective monitor.

**Screenshots**

**Additional context**

**Environment Information (please complete the following information):**
 - macOS version: 10.15.5
 - MonitorControl version: 2.0.0
 - Monitor(s): 2x BENQ BL2711U
Both using mini-DP to HDMI adapters

**Comment by MarkEstefanos** [comment] 2020-06-19 07:23
Same issue with ddcctl.

**Comment by MarkEstefanos** [comment] 2020-06-19 07:25
Same issue with ddcctl. 

`./ddcctl -d 1 -b 35`
and 
`./ddcctl -d 2 -b 35`

both effect only the first external monitor. I also tried digging around the source of MonitorControl a bit to see if I could isolate the bug, but no luck so far.

**Comment by MarkEstefanos** [comment] 2020-06-19 07:47
Looks like this is the bug I'm running into: https://github.com/kfix/ddcctl/issues/17

**Comment by JoniVR** [comment] 2020-06-19 09:03
Duplicate of #49

**Closed by JoniVR** 2020-06-19 09:03 UTC
Labels: Type: Bug
