### ISSUE TITLE
Dell U2723QE: Flickering at 100% brightness

### ISSUE THREAD

**Issue by frogg** [MonitorControl/MonitorControl#1099] opened 2022-07-04 09:58 UTC
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Read through [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the issue

I noticed an unexpected behavior where my Dell U2723QE starts flickering when I set it to 100% brightness via the MonitorControl slider in the menu bar.

First I though it might be a hardware defect, but then I made an experiment:
- enabled advanced settings
- set max DCC brightness to 10 (monitor gets quite dark)
- set the slider to 100% brightness → flickering even at low brightness
- putting the slider at 99% works fine

### Expected behavior

100% brightness without flickering.

### Environment Information (please complete the following information)

```markdown
- macOS version: 12.4 (21F79)
- Mac model: 14“ M1 Pro Macbook Pro
- MonitorControl version: 4.1.0
- Monitor(s): Dell U2723QE
- Monitor Cable(s)/Connection(s): Display Port
- Apple Silicon/M1 (yes or no): yes
```

**Comment by the0neyouseek** [comment] 2022-07-04 10:03
That's weird, I have the same setup (same monitor and device) but I don't have this issue. The only thing different is I'm using an usb-c cable and not a dp one. Maybe try checking with another cable to see if you still have this issue. Also try changing the brightness using the monitor hud to 100% to check if it's also cause a flickering, if it does then it could be a monitor or cable issue.

**Comment by frogg** [comment] 2022-07-04 10:41
Using the monitor’s controls to set brightness to 100% doesn't result in flickering.
Also, actually right now I am not able to reproduce the issue anymore (it started two days ago, and just disappeared).
Not sure why, to be honest. I will report back if it comes back!

**Comment by waydabber** [comment] 2022-07-08 07:49
Hey @frogg - let me know if this returns or if we can file it under `mysteries in life` and close the issue. :)

**Comment by frogg** [comment] 2022-07-08 07:50
Hey @waydabber! So far, all good! If this returns I will reopen this issue :)

**Comment by waydabber** [comment] 2022-07-08 07:52
All right, thanks, I'll close it now then. :)

**Closed by waydabber** 2022-07-08 07:52 UTC
Labels: Type: Monitor Issue, Status: Feedback needed from issue reporter

**Comment by frogg** [comment] 2022-07-16 13:37
Hello, would like to reopen this issue because I can now reproduce it once again:

Changing the brightness manually to 100% using the built-in monitor controls: no flickering.

I noticed however, that MonitorControl seems to constantly dismiss the built-in menu when the flickering is occurring.
My understanding is now, that MC might constantly send the "increase brightness" command in a loop which causes the flickering?

**Comment by frogg** [comment] 2022-11-02 10:20
Hello, this is still an issue that persists until today. Only when increasing the brightness to 100% using MonitorControl, increasing it via the built-in controls of the monitor works fine.
I am on the latest release: `4.1.0`

**Comment by the0neyouseek** [comment] 2022-11-02 10:38
I can confirm this, I saw it too last week, but I can't seem to reproduce it every time

**Comment by frogg** [comment] 2022-11-02 10:41
> I can confirm this, I saw it too last week, but I can't seem to reproduce it every time

Indeed, it seems a bit inconsistent (or maybe it’s just not as notable always).
During the day when it’s generally brighter I don't notice the flickering as much compared to at night.
Also it’s more notable when bright/white content is displayed, in dark mode with lots of dark/black UI elements, its less intense/notable.

**Comment by the0neyouseek** [comment] 2022-11-02 14:43
Okay so this seems to be an issue with the monitor and not with the app as I've got the issue right now and MonitorControl is not launched. Changing brightness with the hud also does not fix the issue.
