### ISSUE TITLE
OSD still shows in 2.0

### ISSUE THREAD

**Issue by izo1** [MonitorControl/MonitorControl#233] opened 2020-06-03 21:46 UTC
In latest 2.0 release, the OSD still shows up on LG 4k UL850 monitor and also macOS OSD on the bottom.

Going back to 1.7.0 fixes the issue

**Comment by MoNTE48** [comment] 2020-06-06 10:02
Same issue MBP 15 2018 + LG 34UC98

**Comment by JoniVR** [comment] 2020-06-06 17:38
Duplicate of #136

**Closed by JoniVR** 2020-06-06 17:38 UTC
