### ISSUE TITLE
Two Asus VZ27A monitors, sliding brightness for each changes same one

### ISSUE THREAD

**Issue by ylluminate** [MonitorControl/MonitorControl#321] opened 2020-11-14 02:27 UTC
I have two Asus VZ27A monitors. The controls for each show up in MonitorControl, but when I alter either of the brightnesses it only manipulates the primary VZ27A. It seems as though MonitorControl is not differentiating between the two devices.

Any thoughts? 

Running on 10.15.7 on a MacPro5,1.

**Comment by AlexKusnezov** [comment] 2020-11-14 09:17
Same here, I have two Samsung U28E850, the id differs only by one digit, but the app still changes only the primary monitors' brightness.

**Comment by ydkn** [comment] 2020-11-14 14:21
Also facing the same issue on a MacBookPro14,2 running macOS 11.0.1 with 2 HP Z27.

**Comment by JoniVR** [comment] 2020-11-20 16:59
Duplicate of #49

**Closed** 2020-11-20 16:59 UTC
Labels: Type: Duplicate

**Comment by ylluminate** [comment] 2020-11-21 06:59
Thanks for pointing this out, I tried to make a comment on that thread, but getting some kind of error so I'll post it here @JoniVR:

Tried the new build and strangely it doesn't even appear in the menubar. The process is running and shows up in Activity Monitor.app. When running from the shell it behaves the same and has the following output:
```
2020-11-21 01:55:48.968 MonitorControl[84770:249524] *** Assertion failure in -[MASPreferencesWindowController initWithWindowNibPath:owner:], /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1894.60.100/Controllers/NSWindowController.m:214
2020-11-21 01:55:48.968 MonitorControl[84770:249524] Invalid parameter not satisfying: windowNibPath
2020-11-21 01:56:00.704 MonitorControl[84770:249524] Warning: Window move completed without beginning
2020-11-21 01:56:03.537 MonitorControl[84770:249524] Warning: Window move completed without beginning
```
