### ISSUE TITLE
Not Working on Macbook Pro screen with Catalina 10.15.7

### ISSUE THREAD

**Issue by starmandeluxe** [MonitorControl/MonitorControl#366] opened 2021-01-07 07:43 UTC
**Checklist**

- [x ] I have searched for existing issues
- [x ] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [ x] I have updated MonitorControl to the latest version

**Describe the bug**
I want to change the brightness of the laptop's screen itself but the menu only shows "No supported display found"

**To Reproduce**
1. Go to the brightness icon in the system top bar
2. Click on the brightness icon
3. Cannot control brightness on the Macbook's monitor

**Expected behavior**
A slider to be able to control the Macbook's monitor brightness (see thread here: https://forums.macrumors.com/threads/menu-bar-brightness-slider.2105286/)

**Screenshots**

**Additional context**

**Environment Information (please complete the following information):**
 - macOS version: Catalina 10.15.7
 - MonitorControl version: 2.1.0
 - Monitor(s): Macbook Pro

**Comment by PrincipeAzzurro** [comment] 2021-02-03 17:57
Same issue here, stopped working after updating to 10.15.7 and applying Apple's last security update.
My monitor is a DELL U4320Q, worked perfectly well before - thank you BTW, MonitorControl is a very welcome piece of software that has made it straight into my "essentials" folder.

**Comment by starmandeluxe** [comment] 2021-02-08 09:23
@PrincipeAzzurro If your issue is with your DELL U4320Q monitor, then your issue is not the same as the one reported in this issue. This issue is for the Macbook Pro screen. Please create a new Github issue if you are using an external monitor.

**Comment by eponymous301** [comment] 2021-02-18 18:20
Might be a general 10.15.7 issue affecting all monitors - I have OS X 10.15.7 on my MacBook Pro (16-inch, 2019), installed MonitorControl (2.1.0 build 721) for the first time, and I see "No supported display found" - neither the laptop's internal display, nor my external USB monitors (AOC, https://us.aoc.com/en/monitors/i1659fwux) seem to be recognized as supporting DDC:

![monitorControl screenshot](https://user-images.githubusercontent.com/29875759/108402750-c9582500-71d2-11eb-84f0-40c252dbb36e.png)

**Comment by LandonSchropp** [comment] 2021-03-15 16:35
I'm having the same issue as the original poster. This app works great when connected to my LG monitor. However, if I *disconnect* from a monitor, I also get a "No supported display found" message for the built-in display.

**Comment by danielyaa5** [comment] 2021-05-10 02:58
experiencing the same thing on 10.15.7

**Comment by danielyaa5** [comment] 2021-05-10 03:02
I just found out you can adjust the laptop screen brightness with control + f1 / f2

**Comment by LandonSchropp** [comment] 2021-05-10 16:07
I wish that I could disable the app when it's not connected to a screen, and enable it when it is. Right now, I quit and restart the app when I plug and unplug.

**Comment by waydabber** [comment] 2021-08-21 14:13
I think this issue is not relevant anymore, so I'll close it but let me know if this issue persists in a comment anyway! Thank you!

@LandonSchropp - this issue was added to the new 3.0.0 version which is out now.

**Closed by waydabber** 2021-08-21 14:13 UTC
Labels: Bug

**Comment by starmandeluxe** [comment] 2021-08-24 02:57
> I think this issue is not relevant anymore, so I'll close it but let me know if this issue persists in a comment anyway! Thank you!
> 
> @LandonSchropp - this issue was added to the new 3.0.0 version which is out now.

@waydabber Your update did not fix the issue. I tried the new version and while I can now see my Macbook Pro built-in screen recognized, there are no brightness controls for it and the preferences for it are grayed out.

**Comment by LandonSchropp** [comment] 2021-08-24 03:22
@starmandeluxe That's odd, it's been working great for me.

Here are my preferences if that's helpful:

<img width="713" alt="Screen Shot 2021-08-23 at 10 18 50 PM" src="https://user-images.githubusercontent.com/361591/130550415-466f06a1-f5a3-41fa-be09-1f63e15ebc63.png">

<img width="710" alt="Screen Shot 2021-08-23 at 10 18 33 PM" src="https://user-images.githubusercontent.com/361591/130550398-8a22cd29-a9e2-42a8-a6bf-fffbc2472c33.png">

I use the built-in keyboard brightness controls to control my MacBook—I'm not sure if you're trying to use a different mechanism such as the slider.

Also, why did you thumbs down most of the comments in this issue?

**Comment by waydabber** [comment] 2021-08-24 07:43
Hi all, the internal screen has no slider by design currently (as it can be controlled by the slider provided by the OS - in Big Sur and up). There is a plan to add the slider as an option:

https://github.com/MonitorControl/MonitorControl/issues/198

Please follow this issue.

Currently if only the internal display is present (there is no external display), MonitorControl disengages from the brightness keys and fully hands back control to the OS as this was an accepted feature request.

Hope this helps! Thank you!

**Comment by waydabber** [comment] 2021-09-03 21:50
There is a build in the following issue thread with slider for built-in screens (and also proper support for Apple displays): https://github.com/MonitorControl/MonitorControl/issues/539
