### ISSUE TITLE
Not Working for 3 Monitors in Mac Mini 2018

### ISSUE THREAD

**Issue by acsusanto** [MonitorControl/MonitorControl#317] opened 2020-11-02 14:18 UTC
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [x] I have updated MonitorControl to the latest version

**Describe the bug**
I am able to control 2 out of the three monitors that are connected to the mac mini. The two monitors connected to usb c works when I use the keys to dim the monitors. But the one with the HDMI cable doesn't work. It stays at the same brightness. I have tried setting it to "Brightness Only" and "Both Brightness and volume", both of them doesn't work.
- I have set "Change Brightness/Volume for all screens" and it still doesn't work with the monitor connected to HDMI 2.0.
- Setting it otherwise still doesn't work as well.

**Environment Information (please complete the following information):**
 - macOS version: 10.15.7
 - MonitorControl version: 2.1.0 (Build 721)
 - Monitor(s): 3

**Comment by JoniVR** [comment] 2020-11-02 18:09
The troubleshooting wiki mentions that HDMI is the least reliable way, this is probably your issue, DDC works best (in my experience) with displayport. Probably not a bug but a cable issue, you can try a different HDMI cable (the cheap ones from Amazon usually don't work) to see if that helps but it's not a guarantee. 

Closing this as I don't feel like this is a bug and it's well documented, feel free to reopen if you feel that my assumption here is wrong.

**Closed by JoniVR** 2020-11-02 18:09 UTC
Labels: Type: Bug

**Comment by acsusanto** [comment] 2020-11-03 01:32
Hi.Thanks for the heads up. Will try your solution.

Yours Sincerely,
Alexander
